connect igadmin/igadmin@IG;

CREATE or replace SYNONYM BROCADE_COLLECT FOR IGADMIN.BROCADE_COLLECT@IG_CST_DBLINK;
CREATE or replace SYNONYM BROCADE_COLLECT_DAY FOR IGADMIN.BROCADE_COLLECT_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM BROCADE_COLLECT_HOUR FOR IGADMIN.BROCADE_COLLECT_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM BROCADE_COLLECT_TEMP FOR IGADMIN.BROCADE_COLLECT_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM BROCADE_TEMP FOR IGADMIN.BROCADE_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_DIR_DA_DAY FOR IGADMIN.VIEW_COLLECT_DIRECTORS_DA_DAY_PERFORMANCE@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_DIR_FIBRE_DAY FOR IGADMIN.VIEW_COLLECT_DIRECTORS_FE_DAY_PERFORMANCE@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_DIR_RFB_DAY FOR IGADMIN.VIEW_COLLECT_DIRECTORS_RDF_DAY_PERFORMANCE@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_DISKS_DAY FOR IGADMIN.VIEW_COLLECT_DISKS_DAY_PERFORMANCE@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_DISKS_LIST FOR IGADMIN.COLLECT_DISKS_LIST@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_OBJECT_LIST FOR IGADMIN.COLLECT_OBJECT_LIST@IG_CST_DBLINK;

CREATE or replace SYNONYM PORT_LEVEL FOR IGADMIN.PORT_LEVEL@IG_CST_DBLINK;
CREATE or replace SYNONYM PORT_LEVEL_DAY FOR IGADMIN.PORT_LEVEL_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM PORT_LEVEL_DAYTEMP FOR IGADMIN.PORT_LEVEL_DAYTEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM PORT_LEVEL_HOUR FOR IGADMIN.PORT_LEVEL_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM PORT_LEVEL_TEMP FOR IGADMIN.PORT_LEVEL_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM RANK_LEVEL FOR IGADMIN.RANK_LEVEL@IG_CST_DBLINK;
CREATE or replace SYNONYM RANK_LEVEL_DAY FOR IGADMIN.RANK_LEVEL_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM RANK_LEVEL_DAYTEMP FOR IGADMIN.RANK_LEVEL_DAYTEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM RANK_LEVEL_HOUR FOR IGADMIN.RANK_LEVEL_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM RANK_LEVEL_TEMP FOR IGADMIN.RANK_LEVEL_TEMP@IG_CST_DBLINK;

CREATE or replace SYNONYM COLLECT_SYMMETRIX_INFO FOR IGADMIN.COLLECT_SYMMETRIX_INFO@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYMMETRIX_MONITOR FOR IGADMIN.COLLECT_SYMMETRIX_MONITOR@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYMMETRIX_MONITOR_DAY FOR IGADMIN.COLLECT_SYMMETRIX_MONITOR_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYMMETRIX_MONITOR_HOUR FOR IGADMIN.COLLECT_SYMMETRIX_MONITOR_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYMMETRIX_MONITOR_RT FOR IGADMIN.COLLECT_SYMMETRIX_MONITOR_RT@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYMMETRIX_MONITOR_TEMP FOR IGADMIN.COLLECT_SYMMETRIX_MONITOR_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM COLLECT_SYSTEM_DAY FOR IGADMIN.COLLECT_SYSTEM_DAY@IG_CST_DBLINK;


CREATE or replace SYNONYM VOLUME_LEVEL FOR IGADMIN.VOLUME_LEVEL@IG_CST_DBLINK;
CREATE or replace SYNONYM VOLUME_LEVEL_DAY FOR IGADMIN.VOLUME_LEVEL_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM VOLUME_LEVEL_DAYTEMP FOR IGADMIN.VOLUME_LEVEL_DAYTEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM VOLUME_LEVEL_HOUR FOR IGADMIN.VOLUME_LEVEL_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM VOLUME_LEVEL_TEMP FOR IGADMIN.VOLUME_LEVEL_TEMP@IG_CST_DBLINK;


CREATE or replace SYNONYM CX_COLLECT_DISK_DAY FOR IGADMIN.CX_COLLECT_DISK_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM CX_COLLECT_ENCLOSURE_DISKS FOR IGADMIN.CX_COLLECT_ENCLOSURE_DISKS@IG_CST_DBLINK;
CREATE or replace SYNONYM CX_COLLECT_PORT_DAY FOR IGADMIN.CX_COLLECT_PORT_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM CX_COLLECT_PORT_NUM FOR IGADMIN.CX_COLLECT_PORT_NUM@IG_CST_DBLINK;
CREATE or replace SYNONYM CX_COLLECT_SP_DAY FOR IGADMIN.CX_COLLECT_SP_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM IBM_VERSION_DATA_MAPPING FOR IGADMIN.IBM_VERSION_DATA_MAPPING@IG_CST_DBLINK;
CREATE or replace SYNONYM IBM_VERSION_LABEL_MAPPING FOR IGADMIN.IBM_VERSION_LABEL_MAPPING@IG_CST_DBLINK;
CREATE or replace SYNONYM MCDATA_COLLECT FOR IGADMIN.MCDATA_COLLECT@IG_CST_DBLINK;
CREATE or replace SYNONYM MCDATA_COLLECT_DAY FOR IGADMIN.MCDATA_COLLECT_DAY@IG_CST_DBLINK;
CREATE or replace SYNONYM MCDATA_COLLECT_HOUR FOR IGADMIN.MCDATA_COLLECT_HOUR@IG_CST_DBLINK;
CREATE or replace SYNONYM MCDATA_COLLECT_TEMP FOR IGADMIN.MCDATA_COLLECT_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM MCDATA_TEMP FOR IGADMIN.MCDATA_TEMP@IG_CST_DBLINK;
CREATE or replace SYNONYM MONITOROBJECT FOR IGADMIN.MONITOROBJECT@IG_CST_DBLINK;
CREATE or replace SYNONYM MONITOROBJECTDEF FOR IGADMIN.MONITOROBJECTDEF@IG_CST_DBLINK;
CREATE or replace SYNONYM MONITOROBJECTDEFVW FOR IGADMIN.MONITOROBJECTDEFVW@IG_CST_DBLINK;
CREATE or replace SYNONYM MONITORTYPE FOR IGADMIN.MONITORTYPE@IG_CST_DBLINK;
CREATE or replace SYNONYM MONITORTYPEDEF FOR IGADMIN.MONITORTYPEDEF@IG_CST_DBLINK;

exit