--填报实例表
CREATE TABLE ig.REGULATORYREPORTINSTANCE
(
	INSTANCEID INTEGER NOT NULL,
	PRTYPE VARCHAR(3),
	KEY VARCHAR(32),
	INITTIME CHAR(16),
	ENDTIME CHAR(16),
	LIMITTIME CHAR(16),
	REMARK VARCHAR(512),
	STATUS CHAR,
	USERID VARCHAR(16),
	USERNAME VARCHAR(32),
	REPORTDESC VARCHAR(64),
	YEAR VARCHAR(4),
	QUARTER VARCHAR(1),
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (INSTANCEID)
);

--填报明细表
CREATE TABLE ig.REGULATORYREPORTDETAIL
(
	DETAILID INTEGER NOT NULL,
	INSTANCEID INTEGER,
	PRID INTEGER,
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (DETAILID),
	FOREIGN KEY (INSTANCEID) REFERENCES ig.REGULATORYREPORTINSTANCE(INSTANCEID)
		ON DELETE CASCADE,
	FOREIGN KEY (PRID) REFERENCES ig.IG500(PRID)
		ON DELETE CASCADE
);

--提醒配置表
CREATE TABLE ig.remindConfigure
(
	rcid INTEGER NOT NULL,
	rcyear VARCHAR(4),
    rcmonth VARCHAR(2),
    rcday VARCHAR(2),
    rctype VARCHAR(2),
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (rcid)
);

--提醒信息表
CREATE TABLE ig.remindInfo
(
  riid INTEGER NOT NULL,
  riuseid VARCHAR(32),
  riinfo VARCHAR(64),
  ristatus VARCHAR(1),
  ritype VARCHAR(1),
  FINGERPRINT VARCHAR(256),
  PRIMARY KEY (riid)
);

--创建sequence序列
--创建年报使用的序列
create sequence ig.PDID_WD1
minvalue 1
maxvalue 9999
start with 1000
increment by 1
cache 20;
--创建季报使用的序列
create sequence ig.PDID_WD2
minvalue 1
maxvalue 9999
start with 1000
increment by 1
cache 20;
--创建不定期报表使用的序列
create sequence ig.PDID_WD3
minvalue 1
maxvalue 9999
start with 1000
increment by 1
cache 20;

CREATE TABLE ig.APPROVESUGGESTION
(
	ID INTEGER NOT NULL,
	PIDID CHAR(10),
	PRID INTEGER,
	PSDCODE CHAR,
	PSDNAME VARCHAR(32),
	SUGGESTION VARCHAR(512),
	STATUS CHAR,
	INSERTTIME CHAR(16),
	USERID VARCHAR(16),
	USERNAME VARCHAR(32),
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (ID),
	FOREIGN KEY (PRID) REFERENCES ig.IG500(PRID)
		ON DELETE CASCADE,
	FOREIGN KEY (PIDID) REFERENCES ig.IG007(PIDID)
		ON DELETE CASCADE
);
alter table ig.ApproveSuggestion add rownumber varchar(32);