

/* Drop Tables */

DROP TABLE RESPONSESTRATEGY;

/* Create Tables */

CREATE TABLE RESPONSESTRATEGY
(
	RSID INTEGER NOT NULL,
	SENCEID INTEGER,
	STRATEGYDESC VARCHAR(2048),
	KEYWORD VARCHAR(128) NOT NULL,
	HANDLEBL VARCHAR(128),
	RSARGS VARCHAR(1024),
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (RSID)
);

--Ôö¼Ó¸æ¾¯ÃèÊö×Ö¶Î
alter table igalarm add column shielddesc varchar(512);

ALTER TABLE ig007 ALTER pidoption SET DATA TYPE varchar(5000);

ALTER TABLE ig380 ALTER pddesc set data type varchar(3000);