------------------------------------------------ 序列-------------------------------
CREATE SEQUENCE SMS_QUEUE_SEQ
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1 NO MAXVALUE;
   
CREATE SEQUENCE SMS_LOG_SEQ
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1 NO MAXVALUE;
   
------------------------------------UPDATE DATE 2012/11/12 短信平台---------------------------
--短信队列表
CREATE TABLE SMS_QUEUE(
  QID INTEGER NOT NULL,
  ALERTID VARCHAR(32),
  TEL VARCHAR(12),
  USERID VARCHAR(32),
  USERNAME VARCHAR(32),
  SMSCONTEXT VARCHAR(1024),
  ALERTTIME VARCHAR(32),
  FINGERPRINT VARCHAR(256), 
  PRIMARY KEY (QID)
);

--短信发送日志表
--SENDTIME系统当前时间--SENDSTATUS发送状态 1_发送成功0_发送失败
CREATE TABLE SEND_SMSLOG(
  ID INTEGER NOT NULL,
  TEL VARCHAR(32),
  USERID VARCHAR(32),
  SMSCONTEXT VARCHAR(1024),
  ALERTTIME VARCHAR(32),
  SENDTIME VARCHAR(32),
  SENDSTATUS INTEGER,
  FINGERPRINT VARCHAR(256), 
  PRIMARY KEY (ID)
);

-------------------------------------------------  MOCHA警报集成表 --------------------------------------------------------------
CREATE TABLE HQ_MOCHA_ALERT(
	ID		DECIMAL(10)  NOT NULL,
	CTIME		VARCHAR(64),
	RTIME		VARCHAR(64),
	IP		VARCHAR(64),
	PLATFORM_ID	DECIMAL(10),
	PLATFORM_NAME	VARCHAR(200),
	FIXED		DECIMAL(1),
	DEFNAME		VARCHAR(200),
	PRIORITY	VARCHAR(128),
	CONDITION	VARCHAR(512),
	VALUE		VARCHAR(32),
	fingerprint varchar(256),
	PRIMARY KEY (ID)
) ;

------------------------------------------------- 机房环境警报集成 --------------------------------------------------------------
CREATE TABLE HQ_JITONG_ALERT(
	eventid			VARCHAR(13)  NOT NULL,
	eventname		VARCHAR(128),
	hisdate 		VARCHAR(23),
	dealrec 		VARCHAR(128),
	prod2realease 		VARCHAR(32),
	reason 			VARCHAR(128),
	dealway 		VARCHAR(128),
	alarmlevel 		DECIMAL(10),
	fingerprint		varchar(25),
	PRIMARY KEY (eventid,hisdate)
) ;

---------------------------------------------------------------监控项目视图---------------------------------------------------
--1.创建平台列表视图

CREATE OR REPLACE VIEW HQ_PLATFORM_LIST_VIEW AS
SELECT
	A.ID AS AGENT_ID,
	CASE WHEN B.PLATFORM_TYPE_ID=10014 THEN B.FQDN ELSE
	A.ADDRESS END AS IP,
	B.ID AS PLATFORM_ID,
	D.NAME,
	B.DESCRIPTION,
	C.NAME AS TYPENAME,
	B.RESOURCE_ID
FROM EAM_AGENT A,EAM_PLATFORM B ,EAM_PLATFORM_TYPE C,EAM_RESOURCE D
WHERE A.ID = B.AGENT_ID AND B.PLATFORM_TYPE_ID = C.ID AND B.RESOURCE_ID = D.ID;

--2. 创建服务器列表视图
CREATE OR REPLACE VIEW HQ_SERVER_LIST_VIEW AS 
SELECT 
	A.ID AS SERVER_ID,
	B.NAME AS TYPENAME,
	C.NAME,
	A.PLATFORM_ID,
	A.RESOURCE_ID,
	B.FVIRTUAL
FROM EAM_SERVER A,EAM_SERVER_TYPE B,EAM_RESOURCE C
WHERE A.SERVER_TYPE_ID = B.ID AND A.RESOURCE_ID = C.ID;


--3. 创建服务列表视图
CREATE OR REPLACE VIEW HQ_SERVICE_LIST_VIEW AS 
SELECT 
	A.ID AS SERVICE_ID,
	B.NAME AS TYPENAME,
	D.NAME,
	A.SERVER_ID,
	C.PLATFORM_ID,
	A.RESOURCE_ID
FROM EAM_SERVICE A,EAM_SERVICE_TYPE B,EAM_SERVER C,EAM_RESOURCE D
WHERE A.SERVICE_TYPE_ID = B.ID AND A.SERVER_ID = C.ID AND A.RESOURCE_ID = D.ID;


--4. 创建所有监控指标列表视图   UPDATE DATE 2012/11/26
CREATE OR REPLACE VIEW HQ_MEASUREMENT_LIST_VIEW AS 
SELECT 
	A.ID,
	B.NAME AS TYPENAME,
	B.ALIAS AS ALIAS,
	B.UNITS,
	A.RESOURCE_ID
FROM EAM_MEASUREMENT A,EAM_MEASUREMENT_TEMPL B,EAM_RESOURCE C
WHERE A.TEMPLATE_ID = B.ID AND A.RESOURCE_ID=C.ID AND A.ENABLED = '1';



--------------------------------------------------------------------  监控指标视图 ------------------------------------------------------------
--1-4 当前平台监控指标视图   UPDATE DATE 2012/11/26
CREATE OR REPLACE VIEW HQ_PLATFORM_M_VIEW AS 
SELECT 
	B.ID,
	A.AGENT_ID,
	A.IP,
	A.PLATFORM_ID,
	A.NAME AS PLATFORM_NAME,
	B.UNITS,
	B.TYPENAME,
	B.RESOURCE_ID
FROM HQ_PLATFORM_LIST_VIEW A,HQ_MEASUREMENT_LIST_VIEW B
WHERE A.RESOURCE_ID = B.RESOURCE_ID;

--2-4 当前服务器监控指标视图  UPDATE DATE 2012/11/26
CREATE OR REPLACE VIEW HQ_SERVER_M_VIEW AS 
SELECT 
	B.ID,
	A.NAME AS SERVER_NAMEM,
	A.TYPENAME AS SERVER_TYPENAME,
	A.PLATFORM_ID,
	A.SERVER_ID,
	A.FVIRTUAL,
	B.UNITS,
	B.TYPENAME,
	B.RESOURCE_ID
FROM HQ_SERVER_LIST_VIEW A, HQ_MEASUREMENT_LIST_VIEW B
WHERE A.RESOURCE_ID = B.RESOURCE_ID;


--3-4 当前服务监控指标视图     UPDATE DATE 2012/11/26------------
CREATE OR REPLACE VIEW HQ_SERVICE_M_VIEW AS 
SELECT 
	A.SERVER_ID,
	B.ID,
	A.PLATFORM_ID,
	A.SERVICE_ID,
	A.TYPENAME AS SERVICE_TYPENAME,
	A.NAME AS SERVICE_NAME,
	B.UNITS,
	B.TYPENAME,
	B.RESOURCE_ID
FROM HQ_SERVICE_LIST_VIEW A, HQ_MEASUREMENT_LIST_VIEW B
WHERE A.RESOURCE_ID = B.RESOURCE_ID;
-------------------------------业务资源监控视图-----------------------------------
--1 被HQ监控的所有对象可用性视图
CREATE OR REPLACE VIEW HQ_AVAILABILITY_VIEW AS 					
SELECT 
	A.MEASUREMENT_ID, 
	A.AVAILVAL, 
	A.STARTIME					
FROM HQ_AVAIL_DATA_RLE A,
	(SELECT MEASUREMENT_ID, MAX(STARTIME) AS STARTIME					
     FROM HQ_AVAIL_DATA_RLE					
     GROUP BY MEASUREMENT_ID) B					
WHERE A.STARTIME = B.STARTIME 
AND A.MEASUREMENT_ID = B.MEASUREMENT_ID;				

--2 业务资源与主机对应关系视图  UPDATE DATE 2012/12/20 ------	
CREATE OR REPLACE VIEW HQ_GROUP_PLATFORM_VIEW AS 				
SELECT D.ID AS GID,	
	D.NAME AS GNAME,				
       C.IP AS PLATFORM_IP,				
       C.PLATFORM_ID AS PLATFORM_ID,				
       C.PLATFORM_NAME,				
       C.ID AS MEASUREMENT_ID,				
       E.AVAILVAL,				
       E.STARTIME,
       G.NAME AS PLATFORM_TYPENAME				
FROM EAM_RESOURCE_GROUP   A,				
       EAM_RES_GRP_RES_MAP  B,				
       HQ_PLATFORM_M_VIEW   C,				
       EAM_RESOURCE         D,				
       HQ_AVAILABILITY_VIEW E,
       EAM_PLATFORM         F,
       EAM_PLATFORM_TYPE    G				
WHERE A.ID = B.RESOURCE_GROUP_ID				
	   AND B.RESOURCE_ID = C.RESOURCE_ID				
	   AND A.RESOURCE_ID = D.ID				
	   AND A.ID > 1				
	   AND C.TYPENAME = 'Availability'				
	   AND C.ID = E.MEASUREMENT_ID		
	   AND C.PLATFORM_ID = F.ID
	   AND F.Platform_Type_Id=G.Id;
	   
	   
--3 平台基本信息视图
CREATE OR REPLACE VIEW HQ_BASE_INFO_VIEW AS 					
SELECT 
	A.APPDEF_ID,
	B.DESCRIPTION,
	A.PROPVALUE,
	B.PROPKEY
FROM EAM_CPROP A, EAM_CPROP_KEY B
WHERE A.KEYID = B.ID;


------------------------------------------------ IP RESOURCE 映射视图UPDATE  DATE 2012/11/07--------------------------------
 CREATE OR REPLACE VIEW HQ_IP_VIEW (NAME,IP,PLATFORM_ID,RESOURCE_ID) AS 
 SELECT NAME,IP,PLATFORM_ID,RESOURCE_ID FROM HQ_PLATFORM_LIST_VIEW A
 UNION ALL 
 SELECT A.NAME,A.IP,A.PLATFORM_ID,B.RESOURCE_ID FROM HQ_PLATFORM_LIST_VIEW A,HQ_SERVER_LIST_VIEW B WHERE A.PLATFORM_ID = B.PLATFORM_ID
 UNION ALL 
 SELECT A.NAME,A.IP,A.PLATFORM_ID,B.RESOURCE_ID FROM HQ_PLATFORM_LIST_VIEW A,HQ_SERVICE_LIST_VIEW B WHERE A.PLATFORM_ID = B.PLATFORM_ID  ;   



--------------------------------- 角色组视图----------------------------------------
create or replace view HQ_SYSTEMGROUP_DETAIL_VIEW as
select A.ID,A.GROUPTYPE,A.RESOURCE_ID,B.NAME,C.RESOURCE_ID as RSID,D.NAME as RSNAME,D.IP,D.PLATFORM_ID as PLID 
from EAM_RESOURCE_GROUP A,
     EAM_RESOURCE B,
     EAM_RES_GRP_RES_MAP C,
     HQ_PLATFORM_LIST_VIEW D 
where A.RESOURCE_ID = B.ID and A.ID = C.RESOURCE_GROUP_ID and C.RESOURCE_ID = D.RESOURCE_ID;


-------------------------
----------------------------------------------------------------- 警报信息视图 -----------------------------------------------------------------------------
--1. 警报列表信息视图 UPDATE DATE 2012/11/07
CREATE OR REPLACE VIEW HQ_ALERT_LIST_VIEW AS
SELECT
       A.ID,A.CTIME,A.FIXED,A.ALERT_DEFINITION_ID,
       B.NAME AS DEFNAME,B.ACTIVE,B.DELETED,B.PRIORITY,RESOURCE_ID,B.ENABLED,
       C.NAME AS CONDNAME,
       C.VERSION_COL,C.TYPE,C.OPTION_STATUS,
       C.COMPARATOR,C.THRESHOLD,
       D.VALUE
FROM
       EAM_ALERT A,
       EAM_ALERT_DEFINITION B,
       (SELECT ID,ALERT_DEFINITION_ID,VERSION_COL,TYPE,OPTION_STATUS,COMPARATOR,THRESHOLD,ARRAY_TO_STRING(ARRAY(SELECT NAME FROM EAM_ALERT_CONDITION C1 WHERE C1.ALERT_DEFINITION_ID = C2.ALERT_DEFINITION_ID ORDER BY ID), ' AND ' ) AS NAME 
       FROM EAM_ALERT_CONDITION C2 GROUP BY ID,ALERT_DEFINITION_ID ORDER BY ID) C,
       (SELECT CONDITION_ID,ALERT_ID,ARRAY_TO_STRING(ARRAY(SELECT VALUE FROM EAM_ALERT_CONDITION_LOG L1 WHERE L1.ALERT_ID = L2.ALERT_ID ORDER BY ID), '#' ) AS VALUE 
       FROM EAM_ALERT_CONDITION_LOG L2 GROUP BY CONDITION_ID,ALERT_ID) D
WHERE
       A.ALERT_DEFINITION_ID = B.ID
       AND B.ID = C.ALERT_DEFINITION_ID
       AND A.ID = D.ALERT_ID;

--2. 警报修复信息视图
CREATE OR REPLACE VIEW HQ_ALERT_FIXED_LIST_VIEW AS 
SELECT 
       A.ID,
       A.CTIME AS ALERT_TIME,
       A.RESOURCE_ID,
       A.FIXED,
       B.TIMESTAMP AS FIXED_TIME,
       B.DETAIL
FROM
       HQ_ALERT_LIST_VIEW A,
       EAM_ALERT_ACTION_LOG B
WHERE A.ID = B.ALERT_ID;


--3 警报详细列表视图
CREATE OR REPLACE VIEW HQ_ALERT_LIST_DETAIL_VIEW AS
SELECT
B.ID,A.IP,A.PLATFORM_ID,A.NAME AS PLATFORM_NAME,B.DEFNAME,B.CTIME,B.VALUE,B.FIXED,B.PRIORITY,
CASE
     WHEN B.TYPE = 4 THEN B.CONDNAME||' value changed'
     WHEN B.TYPE = 1 THEN B.CONDNAME||' '||COMPARATOR||' '||(B.THRESHOLD*100)||'%'
     WHEN B.TYPE = 8 THEN 'Config changed:'||B.OPTION_STATUS
     WHEN B.TYPE = 6 THEN B.CONDNAME||' value changed'
     WHEN B.TYPE = 7 THEN 'Event/Log Level('||
          CASE
               WHEN B.CONDNAME = '-1' THEN 'ANY'
               WHEN B.CONDNAME = '3' THEN 'ERROR'
               WHEN B.CONDNAME = '4' THEN 'WARN'
               WHEN B.CONDNAME = '7' THEN 'DEBUG' END
     ||') and matching substring "'||B.OPTION_STATUS||'"'
END AS Condition,
C.NAME AS BNAME
FROM HQ_IP_VIEW  A, HQ_ALERT_LIST_VIEW B,HQ_SYSTEMGROUP_DETAIL_VIEW C
WHERE A.RESOURCE_ID = B.RESOURCE_ID AND A.PLATFORM_ID = C.PLID AND C.GROUPTYPE = 13; 

 
-------------------------


 ------------------------------------------------全网IP过滤 UPDATE DATE 2012/11/08 ---------------------------
CREATE table HQ_IP_FILTER(
  id          DECIMAL not null,
  ip          VARCHAR(64),
  addtime     VARCHAR(20),
  fingerprint VARCHAR(256)
);
 
---------------可支持监控Server表    UPDATE DATE 2012/11/15
CREATE TABLE HQ_SUPPORT_SERVER_TYPE(
	sstid  DECIMAL(10)  NOT NULL,
	TYPENAME   VARCHAR(64),
	fingerprint VARCHAR(256),
	PRIMARY KEY (sstid)
) ;
 


 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

 
 ------------------------------------------------短信平台触发器 UPDATE DATE 2012/11/12---------------------------

 CREATE OR REPLACE FUNCTION INSERT_SMS_QUEUE_F() 
 	RETURNS TRIGGER AS $$
 DECLARE
  STATUS DECIMAL;
  BEGIN
  SELECT CVALUE INTO STATUS FROM IG.CODEDETAIL WHERE CCID = '153' AND CID = '5';
  IF STATUS = 1 THEN
  INSERT INTO SMS_QUEUE (QID,ALERTID,TEL,USERID,USERNAME,SMSCONTEXT,ALERTTIME)
  SELECT nextval('SMS_QUEUE_SEQ'),
       NEW.ID,
       F.USERMOBILE AS TEL,
       F.USERID AS USERID,
       F.USERNAME,
       CASE
            WHEN G.PRIORITY = 1 THEN '[告警级别:低]'
            WHEN G.PRIORITY = 2 THEN '[告警级别:中]'
            WHEN G.PRIORITY = 3 THEN '[告警级别:高]' END
       ||B.NAME||'_'||A.IP||':'||G.NAME||'('||'#ACTUALVALUE#),产生时间:'||
       TO_CHAR(to_timestamp(NEW.CTIME/1000),'yyyy-MM-dd HH24:MI:SS') AS SMSCONTEXT,
       TO_CHAR(to_timestamp(NEW.CTIME/1000),'yyyy-MM-dd HH24:MI:SS') 
  FROM HQ_IP_VIEW A,
     HQ_SYSTEMGROUP_DETAIL_VIEW B,
     EAM_ROLE_RESOURCE_GROUP_MAP C,
     EAM_SUBJECT_ROLE_MAP D,
     EAM_SUBJECT E,
     IG.IGUSER F,
     EAM_ALERT_DEFINITION G
  WHERE A.PLATFORM_ID=B.PLID
     AND B.GROUPTYPE=13
     AND B.ID=C.RESOURCE_GROUP_ID
     AND C.ROLE_ID=D.ROLE_ID
     AND D.SUBJECT_ID = E.ID
     AND E.NAME = F.USERID
     AND G.RESOURCE_ID = A.RESOURCE_ID
     AND G.ID = NEW.ALERT_DEFINITION_ID;
  END IF;
  RETURN NEW;
  END;
 $$
 LANGUAGE plpgsql;

CREATE TRIGGER INSERT_SMS_QUEUE
  AFTER INSERT ON EAM_ALERT
  FOR EACH ROW EXECUTE PROCEDURE INSERT_SMS_QUEUE_F();
 

  
  ---------------新建MOCHA告警触发器 2012/11/19 ---------------
CREATE OR REPLACE FUNCTION INSERT_SMS_QUEUE_MOCHA_F() 
  RETURNS TRIGGER AS $$
DECLARE
  STATUS DECIMAL;
  BEGIN
  SELECT CVALUE INTO STATUS FROM IG.CODEDETAIL WHERE CCID = '153' AND CID = '5';
  IF STATUS = 1 AND NEW.FIXED = 0 THEN
  INSERT INTO SMS_QUEUE (QID,ALERTID,TEL,USERID,USERNAME,SMSCONTEXT,ALERTTIME)
  SELECT SMS_QUEUE_SEQ.nextval,
       NEW.ID,
       A.USERMOBILE AS TEL,
       A.USERID AS USERID,
       A.USERNAME,
       CASE
            WHEN substr(NEW.PRIORITY,1,1) = 0 THEN '[告警级别:未知]'
            WHEN substr(NEW.PRIORITY,1,1) = 1 THEN '[告警级别:信息]'
            WHEN substr(NEW.PRIORITY,1,1) = 2 THEN '[告警级别:警告]'
            WHEN substr(NEW.PRIORITY,1,1) = 3 THEN '[告警级别:次要]'
            WHEN substr(NEW.PRIORITY,1,1) = 4 THEN '[告警级别:严重]'
            WHEN substr(NEW.PRIORITY,1,1) = 5 THEN '[告警级别:致命]' 
       END
       ||substr(NEW.IP,2,LENGTH(NEW.IP)-2)||':'||substr(NEW.CONDITION,instr(NEW.CONDITION,'报警信息',1,1),
       instr(NEW.CONDITION,'产生时间',1,1)-instr(NEW.CONDITION,'报警信息',1,1))||','||substr(NEW.CONDITION,instr(NEW.CONDITION,'产生时间',1,1),21) AS SMSCONTEXT,
       NEW.CTIME
  FROM IG.IGUSER A,
       IG.ROLE B,
       IG.USERROLE C
  WHERE A.USERID=C.USERID
     AND B.ROLEID=C.ROLEID
     AND B.ROLETYPE='MOCHASMS';
  END IF;
  RETURN NEW;
  END;
 $$
 LANGUAGE plpgsql;
  
CREATE TRIGGER INSERT_SMS_QUEUE_MOCHA
  AFTER INSERT ON HQ_MOCHA_ALERT
  FOR EACH ROW EXECUTE PROCEDURE INSERT_SMS_QUEUE_MOCHA_F();