CREATE OR REPLACE PACKAGE PACK_UPGRADE_PROCESSDEFVERSION IS
-- ######################################################################
-- # 过程名称: 复制/升级流程定义信息
-- # 功能描述: 复制/升级流程定义信息（V_TYPE：0升级，1复制）
-- ######################################################################
  	PROCEDURE PRO_IG380(V_PDID CHAR,  V_PDID_NEW CHAR,  V_TYPE CHAR);
	PROCEDURE PRO_IG007(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG333(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG258(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG211(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG222(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG132(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG881(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG273(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG286(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG413(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG126(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG725(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG699(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG213(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG243(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG298(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG156(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG212(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG237(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG373(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG700(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG701(V_PDID CHAR,  V_PDID_NEW CHAR);
	PROCEDURE PRO_IG911(V_PDID CHAR,  V_PDID_NEW CHAR);
    PROCEDURE PRO_IG931(V_PDID CHAR,  V_PDID_NEW CHAR);
  PROCEDURE PRO_PROCESSDEFVERSION (V_PDID CHAR, V_PDID_NEW CHAR, V_TYPE CHAR);
END PACK_UPGRADE_PROCESSDEFVERSION;
/

CREATE OR REPLACE PACKAGE BODY PACK_UPGRADE_PROCESSDEFVERSION IS
-- ######################################################################
-- # 1.过程名称: 插入IG380
-- # 1.功能描述: 插入IG380
-- ######################################################################
PROCEDURE PRO_IG380 (V_PDID CHAR, V_PDID_NEW CHAR, V_TYPE CHAR) IS
BEGIN
	        INSERT INTO IG380
	        (
	        PDID,
	        PTID,
	        PDNAME,
	        PDDESC,
			PDCRTDATE,
			PDSTATUS,
			PDXML,
			PERMISSION,
			FINGERPRINT,
			SERIALGENERATOR,
			PDACTNAME
	        )
	        SELECT
	        V_PDID_NEW AS PDID_NEW,
	        PTID,
	        CASE WHEN V_TYPE = '1' THEN PDNAME||'-副本' ELSE PDNAME END,
	        PDDESC,
			PDCRTDATE,
			'i',
			REPLACE(PDXML, V_PDID, V_PDID_NEW),
			PERMISSION,
			FINGERPRINT,
			SERIALGENERATOR,
			PDACTNAME
	        FROM IG380 WHERE PDID = V_PDID;
    DBMS_OUTPUT.PUT_LINE('1.复制IG380成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('1.复制IG380失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG380
;

-- ######################################################################
-- # 2.过程名称: 插入IG007
-- # 2.功能描述: 插入IG007
-- ######################################################################
PROCEDURE PRO_IG007 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG007
    (
    PIDID,
	PDID,
	PIDNAME,
	PIDLABEL,
	PIDDESC,
	PIDTYPE,
	PIDOPTION,
	PIDDEFAULT,
	PIDREQUIRED,
	FINGERPRINT,
	PIDSORTID,
	CCID,
	PIDGID,
	PIDMODE,
	PRIVATESCOPE,
	ROWWIDTH
    )
    SELECT
	REPLACE(PIDID, V_PDID, V_PDID_NEW) AS PIDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	PIDNAME,
	PIDLABEL,
	PIDDESC,
	PIDTYPE,
	PIDOPTION,
	PIDDEFAULT,
	PIDREQUIRED,
	FINGERPRINT,
	PIDSORTID,
	CCID,
	PIDGID,
	PIDMODE,
	PRIVATESCOPE,
	ROWWIDTH
    FROM IG007
    WHERE PIDID LIKE V_PDID||'%'
    ORDER BY PIDID;
    DBMS_OUTPUT.PUT_LINE('2.复制IG007成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('2.复制IG007失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG007
;

-- ######################################################################
-- # 3.过程名称: 插入IG333
-- # 3.功能描述: 插入IG333
-- ######################################################################
PROCEDURE PRO_IG333 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG333
    (
	PSDID,
	PDID,
	PSDNAME,
	PSDDESC,
	PSDCODE,
	FINGERPRINT,
	PSDTYPE,
	PSDMODE,
	PSDFLAG,
	PSDASSIGN,
	PSDORG,
	PSDCONFIRM,
	ASSIGNPSDID,
	ASSIGNPBDID,
	ASSIGNFLAG,
	PARTICIPANTCHANGE
    )
    SELECT
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	PSDNAME,
	PSDDESC,
	PSDCODE,
	FINGERPRINT,
	PSDTYPE,
	PSDMODE,
	PSDFLAG,
	PSDASSIGN,
	PSDORG,
	PSDCONFIRM,
	REPLACE(ASSIGNPSDID, V_PDID, V_PDID_NEW) AS ASSIGNPSDID,
	ASSIGNPBDID,
	ASSIGNFLAG,
	PARTICIPANTCHANGE
    FROM IG333
    WHERE PSDID LIKE V_PDID||'%'
    ORDER BY PSDID;
    DBMS_OUTPUT.PUT_LINE('3.复制IG333成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('3.复制IG333失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG333
;

-- ######################################################################
-- # 4.过程名称: 插入IG258
-- # 4.功能描述: 插入IG258
-- ######################################################################
PROCEDURE PRO_IG258 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG258
    (
	PSPCDID,
	PSDID,
	PSPCDPSDID,
	FINGERPRINT
    )
    SELECT
	REPLACE(PSPCDID, V_PDID, V_PDID_NEW) AS PSPCDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	REPLACE(PSPCDPSDID, V_PDID, V_PDID_NEW) AS PSPCDPSDID_NEW,
	FINGERPRINT
    FROM IG258
    WHERE PSPCDID LIKE V_PDID||'%'
    ORDER BY PSPCDID;
    DBMS_OUTPUT.PUT_LINE('4.复制IG258成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('4.复制IG258失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG258
;

-- ######################################################################
-- # 5.过程名称: 插入IG211
-- # 5.功能描述: 插入IG211
-- ######################################################################
PROCEDURE PRO_IG211 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG211
    (
    PSIDID,
	PSDID,
	PIDID,
	PIDNAME,
	PIDLABEL,
	PIDDESC,
	PIDTYPE,
	PIDVALUE,	
	PIDATTKEY,
	FINGERPRINT
    )
    SELECT
	REPLACE(PSIDID, V_PDID, V_PDID_NEW) AS PSIDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	REPLACE(PIDID, V_PDID, V_PDID_NEW) AS PIDID_NEW,
	PIDNAME,
	PIDLABEL,
	PIDDESC,
	PIDTYPE,
	PIDVALUE,	
	PIDATTKEY,
	FINGERPRINT
    FROM IG211
    WHERE PSIDID LIKE V_PDID||'%'
    ORDER BY PSIDID;
    DBMS_OUTPUT.PUT_LINE('5.复制IG211成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('5.复制IG211失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG211
;

-- ######################################################################
-- # 6.过程名称: 插入IG222
-- # 6.功能描述: 插入IG222
-- ######################################################################
PROCEDURE PRO_IG222 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG222
    (
	PPDID,
	PSDID,
	ROLEID,
	USERID,
	PPDSUPER,
	FINGERPRINT
    )
    SELECT
	REPLACE(PPDID, V_PDID, V_PDID_NEW) AS PPDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	ROLEID,
	USERID,
	PPDSUPER,
	FINGERPRINT
    FROM IG222
    WHERE PPDID LIKE V_PDID||'%'
    ORDER BY PPDID;
    DBMS_OUTPUT.PUT_LINE('6.复制IG222成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('6.复制IG222失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG222
;

-- ######################################################################
-- # 7.过程名称: 插入IG132
-- # 7.功能描述: 插入IG132
-- ######################################################################
PROCEDURE PRO_IG132 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG132
    (
	PPBDID,
	PPDID,
	PBDID,
	PPBDNAME,
	PPBDDESC,
	PPBDAUTH,
	FINGERPRINT
    )
    SELECT
	REPLACE(PPBDID, V_PDID, V_PDID_NEW) AS PPBDID_NEW,
	REPLACE(PPDID, V_PDID, V_PDID_NEW) AS PPDID_NEW,
	PBDID,
	PPBDNAME,
	PPBDDESC,
	PPBDAUTH,
	FINGERPRINT
    FROM IG132
    WHERE PPBDID LIKE V_PDID||'%'
    ORDER BY PPBDID;
    DBMS_OUTPUT.PUT_LINE('7.复制IG132成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('7.复制IG132失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG132
;

-- ######################################################################
-- # 8.过程名称: 插入IG881
-- # 8.功能描述: 插入IG881
-- ######################################################################
PROCEDURE PRO_IG881 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG881
    (
	PIPDID,
	PIDID,
	PSDID,
	PPDID,
	PIDACCESS,
	FINGERPRINT,
	PIDREQUIRED
    )
    SELECT
	REPLACE(PIPDID, V_PDID, V_PDID_NEW) AS PIPDID_NEW,
	REPLACE(PIDID, V_PDID, V_PDID_NEW) AS PIDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	REPLACE(PPDID, V_PDID, V_PDID_NEW) AS PPDID_NEW,
	PIDACCESS,
	FINGERPRINT,
	PIDREQUIRED
    FROM IG881
    WHERE PIPDID LIKE V_PDID||'%'
    ORDER BY PIPDID;
    DBMS_OUTPUT.PUT_LINE('8.复制IG881成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('8.复制IG881失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG881
;

-- ######################################################################
-- # 9.过程名称: 插入IG273
-- # 9.功能描述: 插入IG273
-- ######################################################################
PROCEDURE PRO_IG273 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG273
    (
	PTDID,
	FPSDID,
	TPSDID,
	PTDNAME,
	PTDDESC,
	PTDTYPE,
	PTDCOND,
	FINGERPRINT
    )
    SELECT
	REPLACE(PTDID, V_PDID, V_PDID_NEW) AS PTDID_NEW,
	REPLACE(FPSDID, V_PDID, V_PDID_NEW) AS FPSDID_NEW,
	REPLACE(TPSDID, V_PDID, V_PDID_NEW) AS TPSDID_NEW,
	PTDNAME,
	PTDDESC,
	PTDTYPE,
	REPLACE(PTDCOND, V_PDID, V_PDID_NEW) AS PTDCOND,
	FINGERPRINT
    FROM IG273
    WHERE PTDID LIKE V_PDID||'%'
    ORDER BY PTDID;
    DBMS_OUTPUT.PUT_LINE('9.复制IG273成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('9.复制IG273失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG273
;

-- ######################################################################
-- # 10.过程名称: 插入IG286
-- # 10.功能描述: 插入IG286
-- ######################################################################
PROCEDURE PRO_IG286 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG286
    (
	PLID,
	PLDPDID,
	PLDACTIONID,
	INITIATIVEPIDID,
	PASSIVITYPIDID,
	PLDESC,
	PLBLNAME,
	PLJSEVENT,
	PLJTYPE,
	INITIATIVEPIDNAME,
	PASSIVITYPIDNAME,
	FINGERPRINT
    )
    SELECT
	REPLACE(PLID, V_PDID, V_PDID_NEW) AS PLID_NEW,
	V_PDID_NEW AS PLDPDID_NEW,
	PLDACTIONID,
	REPLACE(INITIATIVEPIDID, V_PDID, V_PDID_NEW) AS INITIATIVEPIDID_NEW,
	REPLACE(PASSIVITYPIDID, V_PDID, V_PDID_NEW) AS PASSIVITYPIDID_NEW,
	PLDESC,
	PLBLNAME,
	PLJSEVENT,
	PLJTYPE,
	INITIATIVEPIDNAME,
	PASSIVITYPIDNAME,
	FINGERPRINT
    FROM IG286
    WHERE PLID LIKE V_PDID||'%'
    ORDER BY PLID;
    DBMS_OUTPUT.PUT_LINE('10.复制IG286成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('10.复制IG286失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG286
;

-- ######################################################################
-- # 11.过程名称: 插入IG413
-- # 11.功能描述: 插入IG413
-- ######################################################################
PROCEDURE PRO_IG413 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG413
    (
	PEDID,
	PDID,
	PSDID,
	PEDACTIONID,
	PEDTYPE,
	PEDBLID,
	PEDORDER,
	PEDEC,
	FINGERPRINT
    )
    SELECT
	REPLACE(PEDID, V_PDID, V_PDID_NEW) AS PEDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	PEDACTIONID,
	PEDTYPE,
	PEDBLID,
	PEDORDER,
	PEDEC,
	FINGERPRINT
    FROM IG413
    WHERE PEDID LIKE V_PDID||'%'
    ORDER BY PEDID;
    DBMS_OUTPUT.PUT_LINE('11.复制IG413成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('11.复制IG413失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG413
;

-- ######################################################################
-- # 12.过程名称: 插入IG126
-- # 12.功能描述: 插入IG126
-- ######################################################################
PROCEDURE PRO_IG126 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG126
    (
	PJDID,
	PDID,
	PJDTYPE,
	PJDBLID,
	PJDURL,
	FINGERPRINT
    )
    SELECT
	REPLACE(PJDID, V_PDID, V_PDID_NEW) AS PJDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	PJDTYPE,
	PJDBLID,
	PJDURL,
	FINGERPRINT
    FROM IG126
    WHERE PJDID LIKE V_PDID||'%'
    ORDER BY PJDID;
    DBMS_OUTPUT.PUT_LINE('12.复制IG126成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('12.复制IG126失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG126
;

-- ######################################################################
-- # 13.过程名称: 插入IG725
-- # 13.功能描述: 插入IG725
-- ######################################################################
PROCEDURE PRO_IG725 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG725
    (
    PDBDID,
	PSDID,
	PBDID,
	PDBDNAME,
	PDBDDESC,
	PDBDAUTH,
	FINGERPRINT
    )
    SELECT
	REPLACE(PDBDID, V_PDID, V_PDID_NEW) AS PDBDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	PBDID,
	PDBDNAME,
	PDBDDESC,
	PDBDAUTH,
	FINGERPRINT
    FROM IG725
    WHERE PDBDID LIKE V_PDID||'%'
    ORDER BY PDBDID;
    DBMS_OUTPUT.PUT_LINE('13.复制IG725成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('13.复制IG725失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG725
;

-- ######################################################################
-- # 14.过程名称: 插入IG699
-- # 14.功能描述: 插入IG699
-- ######################################################################
PROCEDURE PRO_IG699 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG699
    (
	PDVID,
	PIDID,
	PSDID,
	PIDACCESS,
	FINGERPRINT,
	PIDREQUIRED
    )
    SELECT
	REPLACE(PDVID, V_PDID, V_PDID_NEW) AS PDVID_NEW,
	REPLACE(PIDID, V_PDID, V_PDID_NEW) AS PIDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	PIDACCESS,
	FINGERPRINT,
	PIDREQUIRED
    FROM IG699
    WHERE PDVID LIKE V_PDID||'%'
    ORDER BY PDVID;
    DBMS_OUTPUT.PUT_LINE('14.复制IG699成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('14.复制IG699失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG699
;

-- ######################################################################
-- # 15.过程名称: 插入IG213
-- # 15.功能描述: 插入IG213
-- ######################################################################
PROCEDURE PRO_IG213 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG213
    (
	PRTDID,
	PDID,
	ROLETYPE,
	FINGERPRINT
    )
    SELECT
	REPLACE(PRTDID, V_PDID, V_PDID_NEW) AS PRTDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	ROLETYPE,
	FINGERPRINT
    FROM IG213
    WHERE PRTDID LIKE V_PDID||'%'
    ORDER BY PRTDID;
    DBMS_OUTPUT.PUT_LINE('15.复制IG213成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('15.复制IG213失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG213
;

-- ######################################################################
-- # 16.过程名称: 插入IG243
-- # 16.功能描述: 插入IG243
-- ######################################################################
PROCEDURE PRO_IG243 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG243
    (
	PTDID,
	PDID,
	PTITLENAME,
	PTITLEACCESS,
	PDESCNAME,
	PDESCACCESS,
	FINGERPRINT
    )
    SELECT
	REPLACE(PTDID, V_PDID, V_PDID_NEW) AS PTDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	PTITLENAME,
	PTITLEACCESS,
	PDESCNAME,
	PDESCACCESS,
	FINGERPRINT
    FROM IG243
    WHERE PTDID LIKE V_PDID||'%'
    ORDER BY PTDID;
    DBMS_OUTPUT.PUT_LINE('16.复制IG243成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('16.复制IG243失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG243
;

-- ######################################################################
-- # 17.过程名称: 插入IG298
-- # 17.功能描述: 插入IG298
-- ######################################################################
PROCEDURE PRO_IG298 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG298
    (
	PSRDID,
	PSDID,
	ROLEID,
	FINGERPRINT
    )
    SELECT
	REPLACE(PSRDID, V_PDID, V_PDID_NEW) AS PSRDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	ROLEID,
	FINGERPRINT
    FROM IG298
    WHERE PSRDID LIKE V_PDID||'%'
    ORDER BY PSRDID;
    DBMS_OUTPUT.PUT_LINE('17.复制IG298成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('17.复制IG298失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG298
;

-- ######################################################################
-- # 18.过程名称: 插入IG156
-- # 18.功能描述: 插入IG156
-- ######################################################################
PROCEDURE PRO_IG156 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG156
    (
	PSEID, 
	PDID, 
	PSDID,
	PSEBUTTONID,
	PSEACTIONID, 
	PSEORDER, 
	PSEDEC, 
	FINGERPRINT,
	PSBDNAME
    )
    SELECT
	REPLACE(PSEID, V_PDID, V_PDID_NEW) AS PSEID_NEW,
	V_PDID_NEW,
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	PSEBUTTONID,
	PSEACTIONID, 
	PSEORDER, 
	PSEDEC, 
	FINGERPRINT,
	PSBDNAME
    FROM IG156
    WHERE PSEID LIKE V_PDID||'%'
    ORDER BY PSEID;
    DBMS_OUTPUT.PUT_LINE('18.复制IG156成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('18.复制IG156失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG156
;

-- ######################################################################
-- # 19.过程名称: 插入IG212
-- # 19.功能描述: 插入IG212
-- ######################################################################
PROCEDURE PRO_IG212 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG212
    (
	PSDID,
	PSDCONFIRM,
	SMS,
	EMAIL,
	NOTIFYD,
	NOTIFYH,
	NOTIFYM,
	REPORTD,
	REPORTH,
	REPORTM,
	ROLEMANAGER,
	FINGERPRINT
    )
    SELECT
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	PSDCONFIRM,
	SMS,
	EMAIL,
	NOTIFYD,
	NOTIFYH,
	NOTIFYM,
	REPORTD,
	REPORTH,
	REPORTM,
	ROLEMANAGER,
	FINGERPRINT
    FROM IG212
    WHERE PSDID LIKE V_PDID||'%'
    ORDER BY PSDID;
    DBMS_OUTPUT.PUT_LINE('19.复制IG212成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('19.复制IG212失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG212
;

-- ######################################################################
-- # 20.过程名称: 插入IG237
-- # 20.功能描述: 插入IG237
-- ######################################################################
PROCEDURE PRO_IG237 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
	        INSERT INTO IG237
	        (
			PSDID,
			PSDCONFIRM,
			USERID,
			ROLEID,
			FINGERPRINT
	        )
	        SELECT
			REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
			PSDCONFIRM,
			USERID,
			ROLEID,
			FINGERPRINT
	        FROM IG237
	        WHERE PSDID LIKE V_PDID||'%'
	        ORDER BY PSDID;
    DBMS_OUTPUT.PUT_LINE('20.复制IG237成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('20.复制IG237失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG237
;

-- ######################################################################
-- # 21.过程名称: 插入IG373
-- # 21.功能描述: 插入IG373
-- ######################################################################
PROCEDURE PRO_IG373 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
	        INSERT INTO IG373
	        (
			PIIDID,
			PDID,
			PSDID,
			PIIDBLID,
			PIIDDEC,
			FINGERPRINT
	        )
	        SELECT
			REPLACE(PIIDID, V_PDID, V_PDID_NEW) AS PIIDID_NEW,
			V_PDID_NEW AS PDID_NEW,
			REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
			PIIDBLID,
			PIIDDEC,
			FINGERPRINT
	        FROM IG373
	        WHERE PSDID LIKE V_PDID||'%'
	        ORDER BY PSDID;
    DBMS_OUTPUT.PUT_LINE('21.复制IG373成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('21.复制IG373失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG373
;

-- ######################################################################
-- # 22.过程名称: 插入IG700
-- # 22.功能描述: 插入IG700
-- ######################################################################
PROCEDURE PRO_IG700 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG700
    (
	PDID, 
	ROLEID,
	FINGERPRINT
    )
    SELECT
	REPLACE(PDID, V_PDID, V_PDID_NEW) AS PDID_NEW,
	ROLEID,
	FINGERPRINT
    FROM IG700
    WHERE PDID LIKE V_PDID||'%'
    ORDER BY PDID;
    DBMS_OUTPUT.PUT_LINE('22.复制IG700成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('22.复制IG700失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG700
;

-- ######################################################################
-- # 23.过程名称: 插入IG701
-- # 23.功能描述: 插入IG701
-- ######################################################################
PROCEDURE PRO_IG701 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG701
    (
	PDID, 
	ROLEID,
	PIDID,
	FINGERPRINT
    )
    SELECT
	REPLACE(PDID, V_PDID, V_PDID_NEW) AS PDID_NEW,
	ROLEID,
	REPLACE(PIDID, V_PDID, V_PDID_NEW) AS PIDID_NEW,
	FINGERPRINT
    FROM IG701
    WHERE PDID LIKE V_PDID||'%'
    ORDER BY PDID;
    DBMS_OUTPUT.PUT_LINE('23.复制IG701成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('23.复制IG701失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG701
;

-- ######################################################################
-- # 24.过程名称: 插入IG911
-- # 24.功能描述: 插入IG911
-- ######################################################################
PROCEDURE PRO_IG911 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG911
    (
    PSPRPID, 
    PDID,
    PSDID,
    ROLEID,
    RELEVANTPDID,
    FINGERPRINT
    )
    SELECT
    REPLACE(PSPRPID, V_PDID, V_PDID_NEW) AS PSPRPID_NEW,
    V_PDID_NEW,
    REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
    ROLEID,
    RELEVANTPDID,
    FINGERPRINT
    FROM IG911
    WHERE PSPRPID LIKE V_PDID||'%'
    ORDER BY PSPRPID;
    DBMS_OUTPUT.PUT_LINE('24.复制IG911成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('24.复制IG911失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG911
;

-- ######################################################################
-- # 25.过程名称: 插入IG931
-- # 25.功能描述: 插入IG931
-- ######################################################################
PROCEDURE PRO_IG931 (V_PDID CHAR, V_PDID_NEW CHAR) IS
BEGIN
    INSERT INTO IG931
    (
    DPSPRPID, 
    PDID,
    PSDID,
    RELEVANTPDID,
    FINGERPRINT
    )
    SELECT
    REPLACE(DPSPRPID, V_PDID, V_PDID_NEW) AS DPSPRPID_NEW,
    V_PDID_NEW,
    REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
    RELEVANTPDID,
    FINGERPRINT
    FROM IG931
    WHERE DPSPRPID LIKE V_PDID||'%'
    ORDER BY DPSPRPID;
    DBMS_OUTPUT.PUT_LINE('25.复制IG931成功。');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('25.复制IG931失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
END PRO_IG931
;

-- ######################################################################
-- # 过程名称: 复制/升级流程定义信息
-- # 功能描述: 复制/升级流程定义信息（V_TYPE：0升级，1复制）
-- ######################################################################
PROCEDURE PRO_PROCESSDEFVERSION (V_PDID CHAR, V_PDID_NEW CHAR, V_TYPE CHAR) IS
BEGIN
	DBMS_OUTPUT.PUT_LINE('=========复制流程开始=========');
	PRO_IG380(V_PDID, V_PDID_NEW, V_TYPE);
	PRO_IG007(V_PDID, V_PDID_NEW);
	PRO_IG333(V_PDID, V_PDID_NEW);
	PRO_IG258(V_PDID, V_PDID_NEW);
	PRO_IG211(V_PDID, V_PDID_NEW);
	PRO_IG222(V_PDID, V_PDID_NEW);
	PRO_IG132(V_PDID, V_PDID_NEW);
	PRO_IG881(V_PDID, V_PDID_NEW);
	PRO_IG273(V_PDID, V_PDID_NEW);
	PRO_IG286(V_PDID, V_PDID_NEW);
	PRO_IG413(V_PDID, V_PDID_NEW);
	PRO_IG126(V_PDID, V_PDID_NEW);
	PRO_IG725(V_PDID, V_PDID_NEW);
	PRO_IG699(V_PDID, V_PDID_NEW);
	PRO_IG213(V_PDID, V_PDID_NEW);
	PRO_IG243(V_PDID, V_PDID_NEW);
	PRO_IG298(V_PDID, V_PDID_NEW);
	PRO_IG156(V_PDID, V_PDID_NEW);
	PRO_IG212(V_PDID, V_PDID_NEW);
	PRO_IG237(V_PDID, V_PDID_NEW);
	PRO_IG373(V_PDID, V_PDID_NEW);
	PRO_IG700(V_PDID, V_PDID_NEW);
	PRO_IG701(V_PDID, V_PDID_NEW);
	PRO_IG911(V_PDID, V_PDID_NEW);
	PRO_IG931(V_PDID, V_PDID_NEW);
  	DBMS_OUTPUT.PUT_LINE('复制流程成功。');
	DBMS_OUTPUT.PUT_LINE('=========复制流程结束=========');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    DBMS_OUTPUT.PUT_LINE('复制流程失败。');
    DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || SQLERRM);
	DBMS_OUTPUT.PUT_LINE('=========复制流程结束=========');
END PRO_PROCESSDEFVERSION
;
END PACK_UPGRADE_PROCESSDEFVERSION;
/