ALTER TABLE IG.IG333 ADD PPSDID CHAR(10);
ALTER TABLE IG.IG333 ADD PSDXML text;
ALTER TABLE IG.IG333 ADD BRANCHCOND CHAR(1);
ALTER TABLE IG.IG224 ADD PSDID CHAR(10);
ALTER TABLE IG.IG224 ADD PPSDID CHAR(10);
ALTER TABLE IG.IG224 ADD VIRTUALSTATUS CHAR(1) DEFAULT '0';
ALTER TABLE IG.IG224 ADD PSDNUM INTEGER;
ALTER TABLE IG.IG337 ADD PSDID CHAR(10);
ALTER TABLE IG.IG337 ADD PSDNUM INTEGER;
ALTER TABLE IG.IG036 ADD PSDID CHAR(10);
ALTER TABLE IG.IG036 ADD PSDNUM INTEGER;
ALTER TABLE IG.IG105 ADD PSDID CHAR(10);
ALTER TABLE IG.IG333 ADD FOREIGN KEY (PPSDID) REFERENCES IG.IG333(PSDID) ON DELETE CASCADE;

CREATE OR REPLACE VIEW "ig".IG591 AS
	WITH T AS (SELECT PRID,PRSTATUS,PSDID,PSDNUM FROM "ig".IG224 T WHERE (T.PRSTATUS = 'C' OR T.PRSTATUS = '#') AND PPSDID IS NULL)
	SELECT PRID,PRSTATUS,PSDID,PSDNUM FROM T
	UNION ALL
	SELECT PRID,PRSTATUS,PSDID,PSDNUM FROM "ig".IG224 A  
	WHERE (VIRTUALSTATUS='0' OR VIRTUALSTATUS IS NULL)AND RSLCLOSETIME IS NULL AND NOT EXISTS (SELECT 1 FROM T WHERE A.PRID = T.PRID)
;
DROP VIEW "ig".IG677
;
DROP VIEW "ig".IG593;

CREATE OR REPLACE VIEW "ig".IG593 AS
	WITH T AS (SELECT PRID,COALESCE(PRSTATUS,'') AS PRSTATUS,PSDID,COALESCE(TRIM(TO_CHAR(PSDNUM,'9')),'') AS PSDNUM,RSLCLOSETIME FROM "ig".IG224 T WHERE (VIRTUALSTATUS='0' OR VIRTUALSTATUS IS NULL) AND RSLCLOSETIME IS NULL)
	SELECT PRID,PRSTATUS,PSDID,PSDNUM, RSLCLOSETIME FROM T
	UNION ALL
	SELECT PRID,COALESCE(PRSTATUS,''),COALESCE(PSDID,''),COALESCE(TRIM(TO_CHAR(PSDNUM,'9')),''),MAX(RSLCLOSETIME) FROM "ig".IG224 A
	WHERE (VIRTUALSTATUS='0' OR VIRTUALSTATUS IS NULL) AND
	NOT EXISTS (SELECT 1 FROM T WHERE A.PRID = T.PRID AND A.PSDID = T.PSDID AND TRIM(TO_CHAR(A.PSDNUM,'9')) = T.PSDNUM AND coalesce(A.PRSTATUS,'') = T.PRSTATUS)
	GROUP BY PRID,PRSTATUS,PSDID,PSDNUM
;

CREATE OR REPLACE VIEW "ig".IG590 AS
	SELECT	A.PRID,A.PRTYPE,A.PRSUBTYPE,A.PRSUBSTATUS,A.PRTITLE,A.PRDESC,A.PROPENTIME,A.PRCLOSETIME,A.PRPLANTIME,A.PRDURATION,A.PRPRIORITY,
			A.PRURGENCY,A.PRIMPACT,A.PRASSETID,A.PRASSETNAME,A.PRASSETCATEGORY,A.PRBUSINESS,A.PRIMPLPLAN,A.PRBACKPLAN,A.PRVFYPLAN,A.PID,
			A.PCODE,A.PNAME,A.PRINFO,A.PRCORID,A.PRCORTYPE,A.PRCORTITLE,A.PRUSERID,A.PRUSERNAME,A.PRROLEID,A.PRROLENAME,A.PRPDID,A.PRPDNAME,
			A.PRORGID,A.PRORGNAME,A.PRSERIALNUM,A.PRFACTTIME,A.FINGERPRINT,A.PRPTDCOND,A.PRSTRATEGYVERSION,
	CASE WHEN MAX(B.PPSUBSTATUS)='1' AND A.PRTYPE='I' AND C.PRSTATUS='E'  THEN 'D' ELSE C.PRSTATUS END AS PRSTATUS
 FROM "ig".IG500 A
 INNER JOIN "ig".IG337 B ON (A.PRID = B.PRID)
 INNER JOIN "ig".IG591 C ON (A.PRID = C.PRID)
 GROUP BY A.PRID,A.PRTYPE,A.PRSUBTYPE,A.PRSUBSTATUS,A.PRTITLE,A.PRDESC,A.PROPENTIME,A.PRCLOSETIME,A.PRPLANTIME,A.PRDURATION,A.PRPRIORITY,
	A.PRURGENCY,A.PRIMPACT,A.PRASSETID,A.PRASSETNAME,A.PRASSETCATEGORY,A.PRBUSINESS,A.PRIMPLPLAN,A.PRBACKPLAN,A.PRVFYPLAN,A.PID,
	A.PCODE,A.PNAME,A.PRINFO,A.PRCORID,A.PRCORTYPE,A.PRCORTITLE,A.PRUSERID,A.PRUSERNAME,A.PRROLEID,A.PRROLENAME,A.PRPDID,A.PRPDNAME,
	A.PRORGID,A.PRORGNAME,A.PRSERIALNUM,A.PRFACTTIME,A.FINGERPRINT,A.PRPTDCOND,A.PRSTRATEGYVERSION,C.PRSTATUS
;

CREATE OR REPLACE VIEW "ig".IG592 AS
	SELECT	A.PRID,A.PRTYPE,A.PRSUBTYPE,A.PRSUBSTATUS,A.PRTITLE,A.PRDESC,A.PROPENTIME,A.PRCLOSETIME,A.PRPLANTIME,A.PRDURATION,A.PRPRIORITY,
			A.PRURGENCY,A.PRIMPACT,A.PRASSETID,A.PRASSETNAME,A.PRASSETCATEGORY,A.PRBUSINESS,A.PRIMPLPLAN,A.PRBACKPLAN,A.PRVFYPLAN,A.PID,
			A.PCODE,A.PNAME,A.PRINFO,A.PRCORID,A.PRCORTYPE,A.PRCORTITLE,A.PRUSERID,A.PRUSERNAME,A.PRROLEID,A.PRROLENAME,A.PRPDID,A.PRPDNAME,
			A.PRORGID,A.PRORGNAME,A.PRSERIALNUM,A.PRFACTTIME,A.FINGERPRINT,A.PRPTDCOND,A.PRSTRATEGYVERSION,
	CASE WHEN MAX(B.PPSUBSTATUS)='1' AND A.PRTYPE='I' AND A.PRSTATUS='E'  THEN 'D' ELSE MAX(C.PRSTATUS) END AS PRSTATUS
 FROM "ig".IG500 A
 INNER JOIN "ig".IG337 B ON (A.PRID = B.PRID)
 INNER JOIN "ig".IG591 C ON (A.PRID = C.PRID)
 GROUP BY A.PRID,A.PRTYPE,A.PRSUBTYPE,A.PRSUBSTATUS,A.PRTITLE,A.PRDESC,A.PROPENTIME,A.PRCLOSETIME,A.PRPLANTIME,A.PRDURATION,A.PRPRIORITY,
	A.PRURGENCY,A.PRIMPACT,A.PRASSETID,A.PRASSETNAME,A.PRASSETCATEGORY,A.PRBUSINESS,A.PRIMPLPLAN,A.PRBACKPLAN,A.PRVFYPLAN,A.PID,
	A.PCODE,A.PNAME,A.PRINFO,A.PRCORID,A.PRCORTYPE,A.PRCORTITLE,A.PRUSERID,A.PRUSERNAME,A.PRROLEID,A.PRROLENAME,A.PRPDID,A.PRPDNAME,
	A.PRORGID,A.PRORGNAME,A.PRSERIALNUM,A.PRFACTTIME,A.FINGERPRINT,A.PRPTDCOND,A.PRSTRATEGYVERSION,A.PRSTATUS
;

CREATE OR REPLACE VIEW "ig".IG677 AS
	SELECT	A.PRID,A.PRTYPE,A.PRSUBTYPE,C.PRSTATUS,A.PRSUBSTATUS,A.PRTITLE,A.PRDESC,A.PROPENTIME,A.PRCLOSETIME,A.PRPLANTIME,A.PRDURATION,A.PRPRIORITY,
			A.PRURGENCY,A.PRIMPACT,A.PRASSETID,A.PRASSETNAME,A.PRASSETCATEGORY,A.PRBUSINESS,A.PRIMPLPLAN,A.PRBACKPLAN,A.PRVFYPLAN,A.PID,
			A.PCODE,A.PNAME,A.PRINFO,A.PRCORID,A.PRCORTYPE,A.PRCORTITLE,A.PRUSERID,A.PRUSERNAME,A.PRROLEID,A.PRROLENAME,A.PRPDID,A.PRPDNAME,
			A.PRORGID,A.PRORGNAME,A.PRSERIALNUM,A.PRFACTTIME,A.PRSTRATEGYVERSION,
			B.PPID,B.PPROLEID,B.PPROLENAME,B.PPUSERID,B.PPUSERNAME,B.PPORGID,B.PPORGNAME,B.PPTYPE,B.PPUSERINFO,B.PPCOMMENT,B.PPATTKEY,
			B.PPINITTIME,B.PPPROCTIME,B.PPSUBSTATUS,B.PPFACTTIME,B.PPBACKTIME,
			CASE 
			WHEN A.PRTYPE='I' AND B.PPSTATUS='E' THEN 
         		CASE WHEN A.PRSTATUS='D' THEN A.PRSTATUS
				ELSE B.PPSTATUS 
				END
			ELSE B.PPSTATUS
			END AS PPSTATUS,C.RSLCLOSETIME,B.PSDID,B.PSDNUM
	FROM	"ig".IG500 A 
	INNER JOIN "ig".IG337 B ON (A.PRID = B.PRID)
	LEFT JOIN "ig".IG593 C ON (A.PRID = C.PRID AND B.PSDID = C.PSDID  AND TRIM(TO_CHAR(B.PSDNUM,'9')) = C.PSDNUM AND B.PPSTATUS = C.PRSTATUS)
;


DELETE FROM  IG.CODEDETAIL WHERE CCID='218' AND CID='5';
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('218', '3', '静态分支节点', '2014/04/28 00:00');
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('218', '4', '动态分支节点', '2014/04/28 00:00');
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('218', '5', '合并节点', '2014/04/28 00:00');
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('218', '6', '子流程节点', '2014/04/28 00:00');
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('224', '0', '角色', '2014/05/13 00:00');
INSERT INTO IG.CODEDETAIL (CCID, CID, CVALUE, UPDTIME) VALUES('224', '1', '人员', '2014/05/13 00:00');
