CREATE TABLE "cst".IBM_VERSION_DATA_MAPPING
(
	ID INTEGER NOT NULL,
	TABLENAME VARCHAR(32),
	COLNAME VARCHAR(32),
	COLINDEX VARCHAR(4),
	DATATYPE VARCHAR(10),
	store	INTEGER,
	PRIMARY KEY (ID)
)TABLESPACE "SOC_SPACE";


CREATE TABLE "cst".IBM_VERSION_LABEL_MAPPING
(
	ID INTEGER NOT NULL,
	LABELNAME VARCHAR(64),
	TABLENAME VARCHAR(32),
	STARTTAG VARCHAR(64),
	INTERVALTIME VARCHAR(64),
	LABELTYPE VARCHAR(10),
	PRIMARY KEY (ID)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Port_Level_Statistics
(  
   DATAID VARCHAR(15) NOT NULL,
   DATA_TIMES VARCHAR(20) NOT NULL,
   SAVE_TIMES VARCHAR(20) NOT NULL,
   Port_ID VARCHAR(15) NOT NULL,
   Speed DECIMAL(26,6),
   IO_Rate DECIMAL(26,6),
   Data_Rate DECIMAL(26,6),	   
   Avg_Resp_Time DECIMAL(26,6),
   FB_Read_IOs DECIMAL(26,6),
   FB_Write_IOs DECIMAL(26,6),
   CKD_Read_IOs DECIMAL(26,6),
   CKD_Write_IOs DECIMAL(26,6),
   PPRC_Receieve_IOs DECIMAL(26,6),
   PPRC_Send_IOs DECIMAL(26,6),
   Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Rank_Level_Statistics
(
        DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Rank_ID VARCHAR(15) NOT NULL,
        RAID_Type  VARCHAR(15) NOT NULL,
        Read_IO_Rate DECIMAL(26,6),
        Write_IO_Rate DECIMAL(26,6),
        Read_Data_Rate DECIMAL(26,6),
        Write_Data_Rate DECIMAL(26,6),
        Avg_Read_Resp_Time DECIMAL(26,6),
        Avg_Write_Resp_Time DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Volume_Level_Statistics
(       
	DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Volume_ID VARCHAR(15) NOT NULL,
        IO_Rate DECIMAL(26,6),
	Data_Rate DECIMAL(26,6),
	Total_Hit_Perc DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";


CREATE TABLE "cst".Collect_Port_Level_Statistics_hour
(  
   DATAID VARCHAR(15) NOT NULL,
   DATA_TIMES VARCHAR(20) NOT NULL,
   SAVE_TIMES VARCHAR(20) NOT NULL,
   Port_ID VARCHAR(15) NOT NULL,
   Speed DECIMAL(26,6),
   IO_Rate DECIMAL(26,6),
   Data_Rate DECIMAL(26,6),	   
   Avg_Resp_Time DECIMAL(26,6),
   FB_Read_IOs DECIMAL(26,6),
   FB_Write_IOs DECIMAL(26,6),
   CKD_Read_IOs DECIMAL(26,6),
   CKD_Write_IOs DECIMAL(26,6),
   PPRC_Receieve_IOs DECIMAL(26,6),
   PPRC_Send_IOs DECIMAL(26,6),
   Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Rank_Level_Statistics_hour
(
        DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Rank_ID VARCHAR(15) NOT NULL,
        RAID_Type  VARCHAR(15) NOT NULL,
        Read_IO_Rate DECIMAL(26,6),
        Write_IO_Rate DECIMAL(26,6),
        Read_Data_Rate DECIMAL(26,6),
        Write_Data_Rate DECIMAL(26,6),
        Avg_Read_Resp_Time DECIMAL(26,6),
        Avg_Write_Resp_Time DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Volume_Level_Statistics_hour
(       
	DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Volume_ID VARCHAR(15) NOT NULL,
        IO_Rate DECIMAL(26,6),
	Data_Rate DECIMAL(26,6),
	Total_Hit_Perc DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";


CREATE TABLE "cst".Collect_Port_Level_Statistics_day
(  
   DATAID VARCHAR(15) NOT NULL,
   DATA_TIMES VARCHAR(20) NOT NULL,
   SAVE_TIMES VARCHAR(20) NOT NULL,
   Port_ID VARCHAR(15) NOT NULL,
   Speed DECIMAL(26,6),
   IO_Rate DECIMAL(26,6),
   Data_Rate DECIMAL(26,6),	   
   Avg_Resp_Time DECIMAL(26,6),
   FB_Read_IOs DECIMAL(26,6),
   FB_Write_IOs DECIMAL(26,6),
   CKD_Read_IOs DECIMAL(26,6),
   CKD_Write_IOs DECIMAL(26,6),
   PPRC_Receieve_IOs DECIMAL(26,6),
   PPRC_Send_IOs DECIMAL(26,6),
   Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Rank_Level_Statistics_day
(
        DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Rank_ID VARCHAR(15) NOT NULL,
        RAID_Type  VARCHAR(15) NOT NULL,
        Read_IO_Rate DECIMAL(26,6),
        Write_IO_Rate DECIMAL(26,6),
        Read_Data_Rate DECIMAL(26,6),
        Write_Data_Rate DECIMAL(26,6),
        Avg_Read_Resp_Time DECIMAL(26,6),
        Avg_Write_Resp_Time DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Volume_Level_Statistics_day
(       
	DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Volume_ID VARCHAR(15) NOT NULL,
        IO_Rate DECIMAL(26,6),
	Data_Rate DECIMAL(26,6),
	Total_Hit_Perc DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Port_Level_Statistics_Daytemp
(  
   DATAID VARCHAR(15) NOT NULL,
   DATA_TIMES VARCHAR(20) NOT NULL,
   SAVE_TIMES VARCHAR(20) NOT NULL,
   Port_ID VARCHAR(15) NOT NULL,
   Speed DECIMAL(26,6),
   IO_Rate DECIMAL(26,6),
   Data_Rate DECIMAL(26,6),	   
   Avg_Resp_Time DECIMAL(26,6),
   FB_Read_IOs DECIMAL(26,6),
   FB_Write_IOs DECIMAL(26,6),
   CKD_Read_IOs DECIMAL(26,6),
   CKD_Write_IOs DECIMAL(26,6),
   PPRC_Receieve_IOs DECIMAL(26,6),
   PPRC_Send_IOs DECIMAL(26,6),
   Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Rank_Level_Statistics_Daytemp
(
        DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Rank_ID VARCHAR(15) NOT NULL,
        RAID_Type  VARCHAR(15) NOT NULL,
        Read_IO_Rate DECIMAL(26,6),
        Write_IO_Rate DECIMAL(26,6),
        Read_Data_Rate DECIMAL(26,6),
        Write_Data_Rate DECIMAL(26,6),
        Avg_Read_Resp_Time DECIMAL(26,6),
        Avg_Write_Resp_Time DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Volume_Level_Statistics_Daytemp
(       
	DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Volume_ID VARCHAR(15) NOT NULL,
        IO_Rate DECIMAL(26,6),
	Data_Rate DECIMAL(26,6),
	Total_Hit_Perc DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";


CREATE TABLE "cst".Collect_Port_Level_Statistics_temp
(  
   DATAID VARCHAR(15) NOT NULL,
   DATA_TIMES VARCHAR(20) NOT NULL,
   SAVE_TIMES VARCHAR(20) NOT NULL,
   Port_ID VARCHAR(15) NOT NULL,
   Speed DECIMAL(26,6),
   IO_Rate DECIMAL(26,6),
   Data_Rate DECIMAL(26,6),	   
   Avg_Resp_Time DECIMAL(26,6),
   FB_Read_IOs DECIMAL(26,6),
   FB_Write_IOs DECIMAL(26,6),
   CKD_Read_IOs DECIMAL(26,6),
   CKD_Write_IOs DECIMAL(26,6),
   PPRC_Receieve_IOs DECIMAL(26,6),
   PPRC_Send_IOs DECIMAL(26,6),
   Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Rank_Level_Statistics_temp
(
        DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Rank_ID VARCHAR(15) NOT NULL,
        RAID_Type  VARCHAR(15) NOT NULL,
        Read_IO_Rate DECIMAL(26,6),
        Write_IO_Rate DECIMAL(26,6),
        Read_Data_Rate DECIMAL(26,6),
        Write_Data_Rate DECIMAL(26,6),
        Avg_Read_Resp_Time DECIMAL(26,6),
        Avg_Write_Resp_Time DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

CREATE TABLE "cst".Collect_Volume_Level_Statistics_temp
(       
	DATAID VARCHAR(15) NOT NULL,
	DATA_TIMES VARCHAR(20) NOT NULL,
        SAVE_TIMES VARCHAR(20) NOT NULL,
	Volume_ID VARCHAR(15) NOT NULL,
        IO_Rate DECIMAL(26,6),
	Data_Rate DECIMAL(26,6),
	Total_Hit_Perc DECIMAL(26,6),
        Interval_Length DECIMAL(26,6)
)TABLESPACE "SOC_SPACE";

create view  "cst".StorageDeviceIDView as 
select dataid,port_id as Director_Number,'port' as type
from  "cst".Collect_Port_Level_Statistics
group by dataid,port_id
union
select dataid,Rank_id as Director_Number,'rank' as type
from "cst".Collect_Rank_Level_Statistics
group by dataid,Rank_id
 union 
select dataid,Volume_ID as Director_Number,'volume' as type
from "cst".Collect_Volume_Level_Statistics
group by dataid,Volume_ID;

ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY ADD COLUMN AVGAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN SUMAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MAXAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MINAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN AVGDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN SUMDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MAXDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MINDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN AVGIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN SUMIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MAXIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_DAY  ADD COLUMN MINIO_RATE DECIMAL (26, 6) ;


ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR ADD COLUMN AVGAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MINAVG_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MINDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_PORT_LEVEL_STATISTICS_HOUR  ADD COLUMN MINIO_RATE DECIMAL (26, 6) ;


ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY ADD COLUMN AVGREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN AVGWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN AVGAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN AVGAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN AVGREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN AVGWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN SUMWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MAXWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_DAY  ADD COLUMN MINWRITE_DATA_RATE DECIMAL (26, 6);


ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR ADD COLUMN AVGREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINREAD_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINWRITE_IO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINAVG_READ_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINAVG_WRITE_RESP_TIME DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINREAD_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXWRITE_DATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_RANK_LEVEL_STATISTICS_HOUR  ADD COLUMN MINWRITE_DATA_RATE DECIMAL (26, 6);


ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY ADD COLUMN AVGDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN SUMDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MAXDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MINDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN AVGIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN SUMIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MAXIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MINIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN AVGTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN SUMTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MAXTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_DAY  ADD COLUMN MINTOTAL_HIT_PERC DECIMAL (26, 6);

ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR ADD COLUMN AVGDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR ADD COLUMN MAXDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN MINDATA_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR ADD   COLUMN AVGIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR ADD COLUMN MAXIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR ADD COLUMN MINIO_RATE DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN AVGTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN SUMTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN MAXTOTAL_HIT_PERC DECIMAL (26, 6);
ALTER TABLE  "cst".COLLECT_VOLUME_LEVEL_STATISTICS_HOUR  ADD COLUMN MINTOTAL_HIT_PERC DECIMAL (26, 6);
