DROP SEQUENCE "ig".UserRegion_seq;
DROP TABLE "ig".UserRegion;
CREATE SEQUENCE "ig".UserRegion_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
CREATE TABLE "ig".UserRegion
(
	ID INTEGER NOT NULL DEFAULT nextval('ig.UserRegion_seq'),
	FLEXID VARCHAR(255) NOT NULL,
	USERID VARCHAR(16),
	X VARCHAR(256),
	Y VARCHAR(256),
	WIDTH VARCHAR(256),
	HEIGHT VARCHAR(256),
	TITLE VARCHAR(256),
	FINGERPRINT VARCHAR(256),
	PRIMARY KEY (ID)
);