insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('1','COLLECT_DEVICES','5772','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('2','COLLECT_DEVICES','5772','KBYTES_READ_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('3','COLLECT_DEVICES','5772','KBYTES_WRITTEN_PER_SEC','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('4','COLLECT_DEVICES','5772','WRITE_PENDING_COUNT','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('5','COLLECT_DEVICES','5772','TOTAL_IOS_PER_SEC','48','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('6','COLLECT_DEVICES','5772','RANDOM_READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('7','COLLECT_DEVICES','5772','RANDOM_WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('8','COLLECT_DEVICES','5772','SEQ_READS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('9','COLLECT_DEVICES','5772','SEQ_WRITES_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('10','COLLECT_DIRECTORS_DA','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('11','COLLECT_DIRECTORS_DA','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('12','COLLECT_DIRECTORS_DA','5772','BUSY','17','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('13','COLLECT_DIRECTORS_DA','5772','interval_time','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('14','COLLECT_DIRECTORS_DA','5772','accumulated_director_idle_time','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('15','COLLECT_DIRECTORS_FE','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('16','COLLECT_DIRECTORS_FE','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('17','COLLECT_DIRECTORS_FE','5772','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('18','COLLECT_DIRECTORS_FE','5772','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('19','COLLECT_DIRECTORS_FE','5772','BUSY','38','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('20','COLLECT_DIRECTORS_FE','5772','INTERVAL_TIME','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('21','COLLECT_DIRECTORS_FE','5772','ACCUMULATED_DIRECTOR_IDLE_TIME','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('22','COLLECT_DIRECTORS_RDF','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('23','COLLECT_DIRECTORS_RDF','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('24','COLLECT_DIRECTORS_RDF','5772','KBYTES_RECEIVED_PER_SEC','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('25','COLLECT_DIRECTORS_RDF','5772','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('26','COLLECT_DIRECTORS_RDF','5772','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('27','COLLECT_DIRECTORS_RDF','5772','BUSY','20','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('28','COLLECT_DIRECTORS_RDF','5772','INTERVAL_TIME','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('29','COLLECT_DIRECTORS_RDF','5772','ACCUMULATED_DIRECTOR_IDLE_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('30','COLLECT_DISKS','5772','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('31','COLLECT_DISKS','5772','TOTAL_SCSI_COMMAND_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('32','COLLECT_DISKS','5772','READ_COMMANDS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('33','COLLECT_DISKS','5772','WRITE_COMMANDS_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('34','COLLECT_DISKS','5772','XOR_WRITE_COMMANDS_PER_SEC','6','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('35','COLLECT_DISKS','5772','XOR_READ_COMMANDS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('36','COLLECT_DISKS','5772','DISK_BUSY','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('37','COLLECT_DISKS','5772','AVERAGE_QUEUE','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('38','COLLECT_DISKS','5772','DISK_IDLE_TIME_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('39','COLLECT_DISKS','5772','ACCUMULATED_QUEUE_DEPTH','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('40','COLLECT_PORTS_FE','5772','PORT_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('41','COLLECT_PORTS_FE','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('42','COLLECT_PORTS_FE','5772','THROUGHPUT_IN_KBYTES_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('43','COLLECT_PORTS_FE','5772','AVERAGE_REQUEST_SIZE_IN_KBYTES','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('44','COLLECT_RDFA_STATUS','5772','RA_GROUP_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('45','COLLECT_RDFA_STATUS','5772','AVG_CYCLE_TIME','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('46','COLLECT_RDFA_STATUS','5772','DURATION_OF_LAST_CYCLE','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('47','COLLECT_RDFA_STATUS','5772','R1_R2_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('48','COLLECT_RDFA_STATUS','5772','R1_R2_MBYTES_PER_SECOND','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('49','COLLECT_RDFA_STATUS','5772','R2_R1_IOS_PER_SEC','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('50','COLLECT_RDFA_STATUS','5772','R2_R1_MBYTES_PER_SECOND','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('51','COLLECT_RDFA_STATUS','5772','TOTAL_CACHE_SLOTS_IN_USE','36','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('52','COLLECT_RDFA_STATUS','5772','ACTIVE_CYCLE_SIZE','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('53','COLLECT_RDFA_STATUS','5772','INACTIVE_CYCLE_SIZE','16','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('54','COLLECT_RDF_DIRECTOR','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('55','COLLECT_RDF_DIRECTOR','5772','KBYTES_READ_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('56','COLLECT_RDF_DIRECTOR','5772','KBYTES_WRITTEN_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('57','COLLECT_RDF_GROUP','5772','RDF_GROUP','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('58','COLLECT_RDF_GROUP','5772','KBYTES_READ_PER_SEC','103','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('59','COLLECT_RDF_GROUP','5772','KBYTES_WRITTEN_PER_SEC','104','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('60','COLLECT_RDF_LINK','5772','LINK_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('61','COLLECT_RDF_LINK','5772','ECHO_DELAY','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('62','COLLECT_RDF_LINK','5772','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('63','COLLECT_RDF_LINK','5772','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('64','COLLECT_SYSTEM','5772','SYMID','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('65','COLLECT_SYSTEM','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('66','COLLECT_SYSTEM','5772','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('67','COLLECT_SYSTEM','5772','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('68','COLLECT_SYSTEM','5772','NUMBER_WRITE_PENDING_TRACKS','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('69','COLLECT_SYSTEM','5772','TOTAL_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('70','COLLECT_SYSTEM','5772','READS_','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('71','COLLECT_SYSTEM','5772','WRITES','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('72','COLLECT_SYSTEM','5772','HIT','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('73','COLLECT_SYSTEM','5772','KBYTES_TRANSFERRED_PER_SEC','27','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('74','COLLECT_SYSTEM','5772','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('75','COLLECT_SYSTEM','5772','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('76','COLLECT_SYSTEM','5772','HITS_PER_SEC','4','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('77','COLLECT_SYSTEM','5772','SEQ_READS_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('78','COLLECT_DIR_ESCON','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('79','COLLECT_DIR_ESCON','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('80','COLLECT_DIR_RA1','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('81','COLLECT_DIR_RA1','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('82','COLLECT_DIR_RA1','5772','KBYTES_RECEIVED_PER_SEC','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('83','COLLECT_DIR_RA1','5772','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('84','COLLECT_DIR_RA1','5772','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('85','COLLECT_DIR_RA1','5772','BUSY','20','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('86','COLLECT_DIR_RA1','5772','INTERVAL_TIME','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('87','COLLECT_DIR_RA1','5772','ACCUMULATED_DIRECTOR_IDLE_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('88','COLLECT_DIR_RA2','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('89','COLLECT_DIR_RA2','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('90','COLLECT_DIR_RA2','5772','KBYTES_RECEIVED_PER_SEC','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('91','COLLECT_DIR_RA2','5772','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('92','COLLECT_DIR_RA2','5772','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('93','COLLECT_DIR_RA2','5772','BUSY','20','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('94','COLLECT_DIR_RA2','5772','INTERVAL_TIME','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('95','COLLECT_DIR_RA2','5772','ACCUMULATED_DIRECTOR_IDLE_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('96','COLLECT_DIR_SA','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('97','COLLECT_DIR_SA','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('98','COLLECT_DIR_SE','5772','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('99','COLLECT_DIR_SE','5772','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('100','COLLECT_DEVICES','5773','DEVICE_NAME','0','EMC');
commit;
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('101','COLLECT_DEVICES','5773','KBYTES_READ_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('102','COLLECT_DEVICES','5773','KBYTES_WRITTEN_PER_SEC','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('103','COLLECT_DEVICES','5773','WRITE_PENDING_COUNT','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('104','COLLECT_DEVICES','5773','TOTAL_IOS_PER_SEC','52','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('105','COLLECT_DEVICES','5773','RANDOM_READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('106','COLLECT_DEVICES','5773','RANDOM_WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('107','COLLECT_DEVICES','5773','SEQ_READS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('108','COLLECT_DEVICES','5773','SEQ_WRITES_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('109','COLLECT_DIRECTORS_DA','5773','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('110','COLLECT_DIRECTORS_DA','5773','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('111','COLLECT_DIRECTORS_DA','5773','BUSY','31','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('112','COLLECT_DIRECTORS_DA','5773','interval_time','20','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('113','COLLECT_DIRECTORS_DA','5773','accumulated_director_idle_time','21','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('114','COLLECT_DIRECTORS_FE','5773','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('115','COLLECT_DIRECTORS_FE','5773','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('116','COLLECT_DIRECTORS_FE','5773','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('117','COLLECT_DIRECTORS_FE','5773','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('118','COLLECT_DIRECTORS_FE','5773','BUSY','45','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('119','COLLECT_DIRECTORS_FE','5773','INTERVAL_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('120','COLLECT_DIRECTORS_FE','5773','ACCUMULATED_DIRECTOR_IDLE_TIME','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('121','COLLECT_DIRECTORS_RDF','5773','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('122','COLLECT_DIRECTORS_RDF','5773','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('123','COLLECT_DIRECTORS_RDF','5773','KBYTES_RECEIVED_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('124','COLLECT_DIRECTORS_RDF','5773','KBYTES_SENT_PER_SEC','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('125','COLLECT_DIRECTORS_RDF','5773','LINK_UTILIZATION','16','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('126','COLLECT_DIRECTORS_RDF','5773','BUSY','30','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('127','COLLECT_DIRECTORS_RDF','5773','INTERVAL_TIME','17','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('128','COLLECT_DIRECTORS_RDF','5773','ACCUMULATED_DIRECTOR_IDLE_TIME','18','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('129','COLLECT_DISKS','5773','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('130','COLLECT_DISKS','5773','TOTAL_SCSI_COMMAND_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('131','COLLECT_DISKS','5773','READ_COMMANDS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('132','COLLECT_DISKS','5773','WRITE_COMMANDS_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('133','COLLECT_DISKS','5773','XOR_WRITE_COMMANDS_PER_SEC','6','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('134','COLLECT_DISKS','5773','XOR_READ_COMMANDS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('135','COLLECT_DISKS','5773','DISK_BUSY','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('136','COLLECT_DISKS','5773','AVERAGE_QUEUE','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('137','COLLECT_DISKS','5773','DISK_IDLE_TIME_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('138','COLLECT_DISKS','5773','ACCUMULATED_QUEUE_DEPTH','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('139','COLLECT_PORTS_FE','5773','PORT_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('140','COLLECT_PORTS_FE','5773','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('141','COLLECT_PORTS_FE','5773','THROUGHPUT_IN_KBYTES_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('142','COLLECT_PORTS_FE','5773','AVERAGE_REQUEST_SIZE_IN_KBYTES','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('143','COLLECT_RDFA_STATUS','5773','RA_GROUP_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('144','COLLECT_RDFA_STATUS','5773','AVG_CYCLE_TIME','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('145','COLLECT_RDFA_STATUS','5773','DURATION_OF_LAST_CYCLE','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('146','COLLECT_RDFA_STATUS','5773','R1_R2_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('147','COLLECT_RDFA_STATUS','5773','R1_R2_MBYTES_PER_SECOND','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('148','COLLECT_RDFA_STATUS','5773','R2_R1_IOS_PER_SEC','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('149','COLLECT_RDFA_STATUS','5773','R2_R1_MBYTES_PER_SECOND','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('150','COLLECT_RDFA_STATUS','5773','TOTAL_CACHE_SLOTS_IN_USE','36','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('151','COLLECT_RDFA_STATUS','5773','ACTIVE_CYCLE_SIZE','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('152','COLLECT_RDFA_STATUS','5773','INACTIVE_CYCLE_SIZE','16','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('153','COLLECT_RDF_DIRECTOR','5773','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('154','COLLECT_RDF_DIRECTOR','5773','KBYTES_READ_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('155','COLLECT_RDF_DIRECTOR','5773','KBYTES_WRITTEN_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('156','COLLECT_RDF_GROUP','5773','RDF_GROUP','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('157','COLLECT_RDF_GROUP','5773','KBYTES_READ_PER_SEC','103','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('158','COLLECT_RDF_GROUP','5773','KBYTES_WRITTEN_PER_SEC','104','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('159','COLLECT_RDF_LINK','5773','LINK_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('160','COLLECT_RDF_LINK','5773','ECHO_DELAY','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('161','COLLECT_RDF_LINK','5773','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('162','COLLECT_RDF_LINK','5773','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('163','COLLECT_SYSTEM','5773','SYMID','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('164','COLLECT_SYSTEM','5773','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('165','COLLECT_SYSTEM','5773','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('166','COLLECT_SYSTEM','5773','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('167','COLLECT_SYSTEM','5773','NUMBER_WRITE_PENDING_TRACKS','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('168','COLLECT_SYSTEM','5773','TOTAL_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('169','COLLECT_SYSTEM','5773','READS_','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('170','COLLECT_SYSTEM','5773','WRITES','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('171','COLLECT_SYSTEM','5773','HIT','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('172','COLLECT_SYSTEM','5773','KBYTES_TRANSFERRED_PER_SEC','27','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('173','COLLECT_SYSTEM','5773','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('174','COLLECT_SYSTEM','5773','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('175','COLLECT_SYSTEM','5773','HITS_PER_SEC','4','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('176','COLLECT_SYSTEM','5773','SEQ_READS_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('177','COLLECT_DEVICES','5671','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('178','COLLECT_DEVICES','5671','KBYTES_READ_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('179','COLLECT_DEVICES','5671','KBYTES_WRITTEN_PER_SEC','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('180','COLLECT_DEVICES','5671','WRITE_PENDING_COUNT','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('181','COLLECT_DEVICES','5671','TOTAL_IOS_PER_SEC','48','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('182','COLLECT_DEVICES','5671','RANDOM_READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('183','COLLECT_DEVICES','5671','RANDOM_WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('184','COLLECT_DEVICES','5671','SEQ_READS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('185','COLLECT_DEVICES','5671','SEQ_WRITES_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('186','COLLECT_DIRECTORS_DA','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('187','COLLECT_DIRECTORS_DA','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('188','COLLECT_DIRECTORS_DA','5671','BUSY','101','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('189','COLLECT_DIRECTORS_DA','5671','interval_time','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('190','COLLECT_DIRECTORS_DA','5671','accumulated_director_idle_time','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('191','COLLECT_DIRECTORS_FE','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('192','COLLECT_DIRECTORS_FE','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('193','COLLECT_DIRECTORS_FE','5671','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('194','COLLECT_DIRECTORS_FE','5671','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('195','COLLECT_DIRECTORS_FE','5671','BUSY','102','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('196','COLLECT_DIRECTORS_FE','5671','INTERVAL_TIME','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('197','COLLECT_DIRECTORS_FE','5671','ACCUMULATED_DIRECTOR_IDLE_TIME','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('198','COLLECT_DIRECTORS_RDF','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('199','COLLECT_DIRECTORS_RDF','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('200','COLLECT_DIRECTORS_RDF','5671','KBYTES_RECEIVED_PER_SEC','10','EMC');
commit;
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('201','COLLECT_DIRECTORS_RDF','5671','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('202','COLLECT_DIRECTORS_RDF','5671','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('203','COLLECT_DIRECTORS_RDF','5671','BUSY','N','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('204','COLLECT_DIRECTORS_RDF','5671','INTERVAL_TIME','N','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('205','COLLECT_DIRECTORS_RDF','5671','ACCUMULATED_DIRECTOR_IDLE_TIME','N','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('206','COLLECT_DISKS','5671','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('207','COLLECT_DISKS','5671','TOTAL_SCSI_COMMAND_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('208','COLLECT_DISKS','5671','READ_COMMANDS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('209','COLLECT_DISKS','5671','WRITE_COMMANDS_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('210','COLLECT_DISKS','5671','XOR_WRITE_COMMANDS_PER_SEC','6','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('211','COLLECT_DISKS','5671','XOR_READ_COMMANDS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('212','COLLECT_DISKS','5671','DISK_BUSY','105','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('213','COLLECT_DISKS','5671','AVERAGE_QUEUE','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('214','COLLECT_DISKS','5671','DISK_IDLE_TIME_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('215','COLLECT_DISKS','5671','ACCUMULATED_QUEUE_DEPTH','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('216','COLLECT_PORTS_FE','5671','PORT_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('217','COLLECT_PORTS_FE','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('218','COLLECT_PORTS_FE','5671','THROUGHPUT_IN_KBYTES_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('219','COLLECT_PORTS_FE','5671','AVERAGE_REQUEST_SIZE_IN_KBYTES','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('220','COLLECT_RDFA_STATUS','5671','RA_GROUP_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('221','COLLECT_RDFA_STATUS','5671','AVG_CYCLE_TIME','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('222','COLLECT_RDFA_STATUS','5671','DURATION_OF_LAST_CYCLE','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('223','COLLECT_RDFA_STATUS','5671','R1_R2_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('224','COLLECT_RDFA_STATUS','5671','R1_R2_MBYTES_PER_SECOND','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('225','COLLECT_RDFA_STATUS','5671','R2_R1_IOS_PER_SEC','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('226','COLLECT_RDFA_STATUS','5671','R2_R1_MBYTES_PER_SECOND','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('227','COLLECT_RDFA_STATUS','5671','TOTAL_CACHE_SLOTS_IN_USE','36','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('228','COLLECT_RDFA_STATUS','5671','ACTIVE_CYCLE_SIZE','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('229','COLLECT_RDFA_STATUS','5671','INACTIVE_CYCLE_SIZE','16','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('230','COLLECT_RDF_DIRECTOR','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('231','COLLECT_RDF_DIRECTOR','5671','KBYTES_READ_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('232','COLLECT_RDF_DIRECTOR','5671','KBYTES_WRITTEN_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('233','COLLECT_RDF_GROUP','5671','RDF_GROUP','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('234','COLLECT_RDF_GROUP','5671','KBYTES_READ_PER_SEC','103','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('235','COLLECT_RDF_GROUP','5671','KBYTES_WRITTEN_PER_SEC','104','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('236','COLLECT_RDF_LINK','5671','LINK_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('237','COLLECT_RDF_LINK','5671','ECHO_DELAY','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('238','COLLECT_RDF_LINK','5671','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('239','COLLECT_RDF_LINK','5671','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('240','COLLECT_SYSTEM','5671','SYMID','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('241','COLLECT_SYSTEM','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('242','COLLECT_SYSTEM','5671','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('243','COLLECT_SYSTEM','5671','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('244','COLLECT_SYSTEM','5671','NUMBER_WRITE_PENDING_TRACKS','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('245','COLLECT_SYSTEM','5671','TOTAL_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('246','COLLECT_SYSTEM','5671','READS_','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('247','COLLECT_SYSTEM','5671','WRITES','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('248','COLLECT_SYSTEM','5671','HIT','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('249','COLLECT_SYSTEM','5671','KBYTES_TRANSFERRED_PER_SEC','27','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('250','COLLECT_SYSTEM','5671','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('251','COLLECT_SYSTEM','5671','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('252','COLLECT_SYSTEM','5671','HITS_PER_SEC','4','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('253','COLLECT_SYSTEM','5671','SEQ_READS_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('254','COLLECT_DIR_ESCON','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('255','COLLECT_DIR_ESCON','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('256','COLLECT_DIR_RA1','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('257','COLLECT_DIR_RA1','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('258','COLLECT_DIR_RA1','5671','KBYTES_RECEIVED_PER_SEC','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('259','COLLECT_DIR_RA1','5671','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('260','COLLECT_DIR_RA1','5671','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('261','COLLECT_DIR_RA1','5671','BUSY','106','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('262','COLLECT_DIR_RA1','5671','INTERVAL_TIME','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('263','COLLECT_DIR_RA1','5671','ACCUMULATED_DIRECTOR_IDLE_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('264','COLLECT_DIR_RA2','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('265','COLLECT_DIR_RA2','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('266','COLLECT_DIR_RA2','5671','KBYTES_RECEIVED_PER_SEC','10','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('267','COLLECT_DIR_RA2','5671','KBYTES_SENT_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('268','COLLECT_DIR_RA2','5671','LINK_UTILIZATION','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('269','COLLECT_DIR_RA2','5671','BUSY','107','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('270','COLLECT_DIR_RA2','5671','INTERVAL_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('271','COLLECT_DIR_RA2','5671','ACCUMULATED_DIRECTOR_IDLE_TIME','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('272','COLLECT_DIR_SA','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('273','COLLECT_DIR_SA','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('274','COLLECT_DIR_SE','5671','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('275','COLLECT_DIR_SE','5671','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('280','COLLECT_DEVICES','5874','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('281','COLLECT_DEVICES','5874','KBYTES_READ_PER_SEC','11','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('282','COLLECT_DEVICES','5874','KBYTES_WRITTEN_PER_SEC','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('283','COLLECT_DEVICES','5874','WRITE_PENDING_COUNT','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('284','COLLECT_DEVICES','5874','TOTAL_IOS_PER_SEC','52','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('285','COLLECT_DEVICES','5874','RANDOM_READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('286','COLLECT_DEVICES','5874','RANDOM_WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('287','COLLECT_DEVICES','5874','SEQ_READS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('288','COLLECT_DEVICES','5874','SEQ_WRITES_PER_SEC','9','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('289','COLLECT_DIRECTORS_DA','5874','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('290','COLLECT_DIRECTORS_DA','5874','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('291','COLLECT_DIRECTORS_DA','5874','BUSY','31','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('292','COLLECT_DIRECTORS_DA','5874','interval_time','20','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('293','COLLECT_DIRECTORS_DA','5874','accumulated_director_idle_time','21','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('294','COLLECT_DIRECTORS_FE','5874','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('295','COLLECT_DIRECTORS_FE','5874','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('296','COLLECT_DIRECTORS_FE','5874','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('297','COLLECT_DIRECTORS_FE','5874','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('298','COLLECT_DIRECTORS_FE','5874','BUSY','45','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('299','COLLECT_DIRECTORS_FE','5874','INTERVAL_TIME','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('300','COLLECT_DIRECTORS_FE','5874','ACCUMULATED_DIRECTOR_IDLE_TIME','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('301','COLLECT_DIRECTORS_RDF','5874','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('302','COLLECT_DIRECTORS_RDF','5874','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('303','COLLECT_DIRECTORS_RDF','5874','KBYTES_RECEIVED_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('304','COLLECT_DIRECTORS_RDF','5874','KBYTES_SENT_PER_SEC','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('305','COLLECT_DIRECTORS_RDF','5874','LINK_UTILIZATION','16','EMC');
commit;
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('306','COLLECT_DIRECTORS_RDF','5874','BUSY','30','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('307','COLLECT_DIRECTORS_RDF','5874','INTERVAL_TIME','17','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('308','COLLECT_DIRECTORS_RDF','5874','ACCUMULATED_DIRECTOR_IDLE_TIME','18','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('309','COLLECT_DISKS','5874','DEVICE_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('310','COLLECT_DISKS','5874','TOTAL_SCSI_COMMAND_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('311','COLLECT_DISKS','5874','READ_COMMANDS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('312','COLLECT_DISKS','5874','WRITE_COMMANDS_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('313','COLLECT_DISKS','5874','XOR_WRITE_COMMANDS_PER_SEC','6','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('314','COLLECT_DISKS','5874','XOR_READ_COMMANDS_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('315','COLLECT_DISKS','5874','DISK_BUSY','22','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('316','COLLECT_DISKS','5874','AVERAGE_QUEUE','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('317','COLLECT_DISKS','5874','DISK_IDLE_TIME_PER_SEC','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('318','COLLECT_DISKS','5874','ACCUMULATED_QUEUE_DEPTH','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('319','COLLECT_PORTS_FE','5874','PORT_NAME','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('320','COLLECT_PORTS_FE','5874','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('321','COLLECT_PORTS_FE','5874','THROUGHPUT_IN_KBYTES_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('322','COLLECT_PORTS_FE','5874','AVERAGE_REQUEST_SIZE_IN_KBYTES','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('323','COLLECT_RDFA_STATUS','5874','RA_GROUP_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('324','COLLECT_RDFA_STATUS','5874','AVG_CYCLE_TIME','12','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('325','COLLECT_RDFA_STATUS','5874','DURATION_OF_LAST_CYCLE','13','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('326','COLLECT_RDFA_STATUS','5874','R1_R2_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('327','COLLECT_RDFA_STATUS','5874','R1_R2_MBYTES_PER_SECOND','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('328','COLLECT_RDFA_STATUS','5874','R2_R1_IOS_PER_SEC','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('329','COLLECT_RDFA_STATUS','5874','R2_R1_MBYTES_PER_SECOND','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('330','COLLECT_RDFA_STATUS','5874','TOTAL_CACHE_SLOTS_IN_USE','36','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('331','COLLECT_RDFA_STATUS','5874','ACTIVE_CYCLE_SIZE','15','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('332','COLLECT_RDFA_STATUS','5874','INACTIVE_CYCLE_SIZE','16','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('333','COLLECT_RDF_DIRECTOR','5874','DIRECTOR_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('334','COLLECT_RDF_DIRECTOR','5874','KBYTES_READ_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('335','COLLECT_RDF_DIRECTOR','5874','KBYTES_WRITTEN_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('336','COLLECT_RDF_GROUP','5874','RDF_GROUP','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('337','COLLECT_RDF_GROUP','5874','KBYTES_READ_PER_SEC','103','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('338','COLLECT_RDF_GROUP','5874','KBYTES_WRITTEN_PER_SEC','104','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('339','COLLECT_RDF_LINK','5874','LINK_NUMBER','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('340','COLLECT_RDF_LINK','5874','ECHO_DELAY','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('341','COLLECT_RDF_LINK','5874','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('342','COLLECT_RDF_LINK','5874','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('343','COLLECT_SYSTEM','5874','SYMID','0','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('344','COLLECT_SYSTEM','5874','IOS_PER_SEC','1','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('345','COLLECT_SYSTEM','5874','KBYTES_READ_PER_SEC','7','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('346','COLLECT_SYSTEM','5874','KBYTES_WRITTEN_PER_SEC','8','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('347','COLLECT_SYSTEM','5874','NUMBER_WRITE_PENDING_TRACKS','14','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('348','COLLECT_SYSTEM','5874','TOTAL_IOS_PER_SEC','23','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('349','COLLECT_SYSTEM','5874','READS_','24','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('350','COLLECT_SYSTEM','5874','WRITES','25','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('351','COLLECT_SYSTEM','5874','HIT','26','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('352','COLLECT_SYSTEM','5874','KBYTES_TRANSFERRED_PER_SEC','27','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('353','COLLECT_SYSTEM','5874','READS_PER_SEC','2','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('354','COLLECT_SYSTEM','5874','WRITES_PER_SEC','3','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('355','COLLECT_SYSTEM','5874','HITS_PER_SEC','4','EMC');
insert into IGADMIN.VERSION_DATA_MAPPING (ID,NAME,MICROCODE,COLNAME,VINDEX,TYPE) 
values ('356','COLLECT_SYSTEM','5874','SEQ_READS_PER_SEC','9','EMC');
commit;