insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('1','5772','SYMMETRIX','<SYMMETRIX','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('2','5772','TIMESTAMP','<TIMESTAMP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('3','5772','TIME INTERVAL','<TIME INTERVAL>','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('4','5772','DATA: SYSTEM','<DATA: SYSTEM','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('5','5772','DATA: DEVICES','<DATA: DEVICES','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('6','5772','DATA: DIR-FIBRE','<DATA: DIR-FIBRE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('7','5772','DATA: DIR-SA','<DATA: DIR-SA','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('8','5772','DATA: DIR-SE','<DATA: DIR-SE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('9','5772','DATA: DIR-DA','<DATA: DIR-DA','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('10','5772','DATA: DIR-ESCON','<DATA: DIR-ESCON','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('11','5772','DATA: DIR-RA1','<DATA: DIR-RA1','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('12','5772','DATA: DIR-RA2','<DATA: DIR-RA2','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('13','5772','DATA: DIR-RFB','<DATA: DIR-RFB','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('14','5772','DATA: DISKS','<DATA: DISKS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('15','5772','DATA: DIR-PORT','<DATA: DIR-PORT','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('16','5772','DATA: RDFASTATS','<DATA: RDFASTATS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('17','5772','DATA: RDF-DIRECTOR','<DATA: RDF-DIRECTOR','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('18','5772','DATA: RDF-LINK','<DATA: RDF-LINK','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('19','5772','DATA: RDF-GROUP','<DATA: RDF-GROUP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('20','5773','SYMMETRIX','<SYMMETRIX','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('21','5773','TIMESTAMP','<TIMESTAMP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('22','5773','TIME INTERVAL','<TIME INTERVAL>','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('23','5773','DATA: SYSTEM','<DATA: SYSTEM','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('24','5773','DATA: DEVICES','<DATA: DEVICES','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('25','5773','DATA: DIR-FIBRE','<DATA: DIRECTORS FE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('26','5773','DATA: DIR-DA','<DATA: DIRECTORS BE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('27','5773','DATA: DIR-RFB','<DATA: DIRECTORS RDF','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('28','5773','DATA: DISKS','<DATA: DISKS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('29','5773','DATA: DIR-PORT','<DATA: PORTS FE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('30','5773','DATA: RDFASTATS','<DATA: RDFASTATS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('31','5773','DATA: RDF-DIRECTOR','<DATA: RDF-DIRECTOR','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('32','5773','DATA: RDF-LINK','<DATA: RDF-LINK','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('33','5773','DATA: RDF-GROUP','<DATA: RDF-GROUP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('34','5671','SYMMETRIX','<SYMMETRIX','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('35','5671','TIMESTAMP','<TIMESTAMP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('36','5671','TIME INTERVAL','<TIME INTERVAL>','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('37','5671','DATA: SYSTEM','<DATA: SYSTEM','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('38','5671','DATA: DEVICES','<DATA: DEVICES','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('39','5671','DATA: DIR-FIBRE','<DATA: DIR-FIBRE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('40','5671','DATA: DIR-SA','<DATA: DIR-SA','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('41','5671','DATA: DIR-SE','<DATA: DIR-SE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('42','5671','DATA: DIR-DA','<DATA: DIR-DA','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('43','5671','DATA: DIR-ESCON','<DATA: DIR-ESCON','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('44','5671','DATA: DIR-RA1','<DATA: DIR-RA1','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('45','5671','DATA: DIR-RA2','<DATA: DIR-RA2','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('46','5671','DATA: DIR-RFB','<DATA: DIR-RFB','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('47','5671','DATA: DISKS','<DATA: DISKS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('48','5671','DATA: DIR-PORT','<DATA: DIR-PORT','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('49','5671','DATA: RDFASTATS','<DATA: RDFASTATS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('50','5671','DATA: RDF-DIRECTOR','<DATA: RDF-DIRECTOR','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('51','5671','DATA: RDF-LINK','<DATA: RDF-LINK','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('52','5671','DATA: RDF-GROUP','<DATA: RDF-GROUP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('53','5874','SYMMETRIX','<SYMMETRIX','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('54','5874','TIMESTAMP','<TIMESTAMP','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('55','5874','TIME INTERVAL','<TIME INTERVAL>','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('56','5874','DATA: SYSTEM','<DATA: SYSTEM','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('57','5874','DATA: DEVICES','<DATA: DEVICES','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('58','5874','DATA: DIR-FIBRE','<DATA: DIRECTORS FE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('59','5874','DATA: DIR-DA','<DATA: DIRECTORS BE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('60','5874','DATA: DIR-RFB','<DATA: DIRECTORS RDF','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('61','5874','DATA: DISKS','<DATA: DISKS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('62','5874','DATA: DIR-PORT','<DATA: PORTS FE','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('63','5874','DATA: RDFASTATS','<DATA: RDFASTATS','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('64','5874','DATA: RDF-DIRECTOR','<DATA: RDF-DIRECTOR','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('65','5874','DATA: RDF-LINK','<DATA: RDF-LINK','EMC');
insert into IGADMIN.VERSION_LABEL_MAPPING (ID,MICROCODE,NAME,LABEL,TYPE) 
values ('66','5874','DATA: RDF-GROUP','<DATA: RDF-GROUP','EMC');
commit;