
package com.openmind.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendServiceImpl", targetNamespace = "http://service.openmind.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send", targetNamespace = "http://service.openmind.com/", className = "com.openmind.service.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://service.openmind.com/", className = "com.openmind.service.SendResponse")
    @Action(input = "http://service.openmind.com/SendServiceImpl/sendRequest", output = "http://service.openmind.com/SendServiceImpl/sendResponse")
    public String send();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMessageText", targetNamespace = "http://service.openmind.com/", className = "com.openmind.service.SetMessageText")
    @ResponseWrapper(localName = "setMessageTextResponse", targetNamespace = "http://service.openmind.com/", className = "com.openmind.service.SetMessageTextResponse")
    @Action(input = "http://service.openmind.com/SendServiceImpl/setMessageTextRequest", output = "http://service.openmind.com/SendServiceImpl/setMessageTextResponse")
    public void setMessageText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
