CREATE OR REPLACE TRIGGER TRIG_002
  AFTER UPDATE ON IG500  
  FOR EACH ROW
DECLARE
  STATUS     VARCHAR(10);
  STATUSDESC VARCHAR(128);
BEGIN
  IF :NEW.PRSTATUS = 'C' AND :NEW.PRSUBSTATUS = 'C' THEN
    STATUS     := 'C1';
    STATUSDESC := '已经关闭（中止）';
  ELSIF :NEW.PRTYPE = 'C' AND :NEW.PRSTATUS = 'C' THEN
    IF :NEW.PRSUBSTATUS = 'S' THEN
      STATUS     := 'C2';
      STATUSDESC := '已经关闭（成功）';
    ELSIF :NEW.PRSUBSTATUS = 'F' THEN
      STATUS     := 'C3';
      STATUSDESC := '已经关闭（失败）';
    ELSIF :NEW.PRSUBSTATUS = 'P' THEN
      STATUS     := 'C4';
      STATUSDESC := '已经关闭（存在问题）';
    END IF;
  ELSIF :NEW.PRTYPE = 'D' AND :NEW.PRSTATUS = 'C' THEN
    IF :NEW.PRSUBSTATUS = 'S' THEN
      STATUS     := 'C2';
      STATUSDESC := '已经关闭（成功）';
    ELSIF :NEW.PRSUBSTATUS = 'F' THEN
      STATUS     := 'C3';
      STATUSDESC := '已经关闭（失败）';
    ELSIF :NEW.PRSUBSTATUS = 'P' THEN
      STATUS     := 'C4';
      STATUSDESC := '已经关闭（存在问题）';
    END IF;
  ELSE
    STATUS := :NEW.PRSTATUS;
    SELECT PSDNAME
      INTO STATUSDESC
      FROM IG173
     WHERE PDID = :NEW.PRPDID
       AND PSDCODE = :NEW.PRSTATUS;
  END IF;
  UPDATE R01
     SET R0104 = STATUS, R0118 = STATUSDESC, R0108 = :NEW.PRCLOSETIME
   WHERE R0102 = :NEW.PRID;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END TRIG_002;
/
