CREATE OR REPLACE TRIGGER TRIG_005
  AFTER INSERT ON IG599
  FOR EACH ROW
DECLARE
  FLAG INT := 0;
BEGIN
  IF :NEW.PIDMODE = '0' THEN
    SELECT COUNT(1)
      INTO FLAG
      FROM IG500 IG500
     INNER JOIN IG380 B ON (IG500.PRPDID = B.PDID)
     WHERE B.PDSTATUS = 'a'
       AND IG500.PRID = :NEW.PRID;
    IF FLAG = 1 THEN
      INSERT INTO R02
        (R0201, R0202, R0203, R0204, R0205, R0206, R0207, R0208, R0209)
      VALUES
        (:NEW.PIID,
         :NEW.PRID,
         :NEW.PIVARNAME,
         :NEW.PIVARLABEL,
         :NEW.PIVARVALUE,
         :NEW.PIDMODE,
         0,
         NULL,
         NULL);
    END IF;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END TRIG_005;
/
