CREATE OR REPLACE TRIGGER TRIG_006
  AFTER UPDATE ON IG599
  FOR EACH ROW
BEGIN
  UPDATE R02 A SET R0205 = :NEW.PIVARVALUE WHERE R0201 = :NEW.PIID;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END TRIG_006;
/
