CREATE OR REPLACE TRIGGER TRIG_004
  AFTER UPDATE ON IG337
  FOR EACH ROW
BEGIN
  UPDATE R01
     SET R0112 = :NEW.PPROLEID,
         R0113 = :NEW.PPROLENAME,
         R0114 = :NEW.PPUSERID,
         R0115 = :NEW.PPUSERNAME,
         R0116 = :NEW.PPORGID,
         R0117 = (SELECT ORGNAME FROM ORGANIZATION WHERE ORGID = :NEW.PPORGID),
         R0121 = :NEW.PPINITTIME,
         R0122 = :NEW.PPPROCTIME,
         R0123 = :NEW.PPSUBSTATUS,
         R0124 = :NEW.PPBACKTIME,
         R0125 = :NEW.PPPROXYUSERID,
         R0126 = :NEW.PPSUPER,
         R0127 = :NEW.PPROLEMANAGER,
         R0128 = :NEW.PPDUTYPERSON,
         R0129 = :NEW.PBDID,
         R0130 = (SELECT USERNAME
                    FROM IGUSER
                   WHERE USERID = :NEW.PPPROXYUSERID)
   WHERE R0101 = :NEW.PPID;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END TRIG_004;
/
