CREATE OR REPLACE TRIGGER TRIG_009
  AFTER DELETE ON IG500
  FOR EACH ROW
BEGIN
  DELETE FROM R01 WHERE R0102 = :OLD.PRID;
  DELETE FROM R02 WHERE R0202 = :OLD.PRID;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END TRIG_009;
/
