--ig259
INSERT INTO IG259
(PTID, PTNAME, PTTYPE, PTSTARTPG, PTDETAILPG, PTCRTDATE, PTPICINFO, PTSTATUS, PTSAVEPG, PTQRTZFLAG, FIRSTSITE, PDSEQUENCE, FINGERPRINT)
VALUES(20, '应急管理', 'DRM', 'IGPRR0102_Disp.do?psdcode=Z&ptid=20&pdid=', 'IGPRR0102_Disp.do?prtype=DRM&prid=', '2015/04/20', NULL, 'a', NULL, NULL, '0', 'PDID_SEQ', NULL);
INSERT INTO IG259
(PTID, PTNAME, PTTYPE, PTSTARTPG, PTDETAILPG, PTCRTDATE, PTPICINFO, PTSTATUS, PTSAVEPG, PTQRTZFLAG, FIRSTSITE, PDSEQUENCE, FINGERPRINT)
VALUES(22, '应急处置', 'WDP', 'IGPRR0102_Disp.do?psdcode=Z&ptid=22&pdid=', 'IGPRR0102_Disp.do?prtype=WDP&prid=', '2014/05/19', NULL, 'a', NULL, NULL, '0', 'PDID_SEQ', NULL);
INSERT INTO IG259
(PTID, PTNAME, PTTYPE, PTSTARTPG, PTDETAILPG, PTCRTDATE, PTPICINFO, PTSTATUS, PTSAVEPG, PTQRTZFLAG, FIRSTSITE, PDSEQUENCE, FINGERPRINT)
VALUES(21, '指挥流程', 'WDC', 'IGPRR0102_Disp.do?psdcode=Z&ptid=21&pdid=', 'IGPRR0102_Disp.do?prtype=WDC&prid=', '2014/05/19', NULL, 'a', NULL, NULL, '0', 'PDID_SEQ', NULL);



 



-- 设备资产属性类型
  INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('008', '010', '安全属性', NULL, NULL, '2010/01/01 00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('008', '009', '关联关系', NULL, NULL, '2010/01/01 00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('008', '011', '机房属性', NULL, NULL, '2015/05/07 00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('008', '008', '容灾属性', NULL, NULL, '2010/01/01 00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--CODEDETAIL角色类型
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('100', 'IGBP50', '应急管理', NULL, NULL, '2015/02/27 00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--mina基础数据
INSERT INTO DB2INST1.CODECATEGORY (CCID,CCNAME,CCINFO,CCEDITABLE,PCCID,PCFLAG,FINGERPRINT) VALUES 
('174','Mina服务器配置',NULL,'3',NULL,'0',NULL);
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('174', '2', '57.0.6.43', NULL, NULL, '2015/07/15 11:18', NULL, NULL, NULL, NULL, NULL, 'Mina服务IP', NULL);
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('174', '1', '7911', NULL, NULL, '2014/10/11 11:55', NULL, NULL, NULL, NULL, NULL, 'Mina服务端口号', NULL);
--codedetail 资产关系码
INSERT INTO CODEDETAIL
(CCID, CID, CVALUE, PCCID, PCID, UPDTIME, SYSCODING, PSYSCODING, CDSTATUS, BUSINESSCODE, FINGERPRINT, CDINFO, CDORDER)
VALUES('050', '01', '专项预案-场景', NULL, NULL, '2015/03/09 00:00', NULL, NULL, NULL, '050-060', NULL, NULL, NULL);

--组织架构基础数据
INSERT INTO  CODECATEGORYDEF (ccid, ccname, ccinfo, cceditable, pccid, pcflag)
values ('230', '应急组织架构', null, '3', null, '4');


insert into CODECATEGORYDEF (ccid, ccname, ccinfo, cceditable, pccid, pcflag, fingerprint)
values ('231', '一级分类', '一级分类', '3', '230', '4', null);
insert into CODECATEGORYDEF (ccid, ccname, ccinfo, cceditable, pccid, pcflag, fingerprint)
values ('232', '二级分类', '二级分类', '3', '231', '4', null);
insert into CODECATEGORYDEF (ccid, ccname, ccinfo, cceditable, pccid, pcflag, fingerprint)
values ('233', '三级分类', '三级分类', '3', '232', '4', null);

INSERT INTO DB2INST1.CODEDETAILDEF (CCID,CID,CVALUE,PCCID,PCID,UPDTIME,SYSCODING,PSYSCODING,CDSTATUS,BUSINESSCODE,CDINFO,FINGERPRINT) VALUES 
('230','0001','应急决策层',NULL,NULL,'2016/04/13 14:39','230001',NULL,'1',NULL,NULL,NULL)
,('230','0002','应急领导层',NULL,'','2016/08/15 17:16','230002','','1','',NULL,NULL)
,('230','0003','应急指挥层',NULL,'','2016/08/15 17:17','230003','','1','',NULL,NULL)
,('230','0004','应急执行层',NULL,'','2016/08/15 17:17','230004','','1','',NULL,NULL)
,('230','0005','应急保障层',NULL,'','2016/08/15 17:17','230005','','1','',NULL,NULL)
;



--应急资源顶级模型
INSERT INTO EMERGENCYRESOURCE
(ERID, ESYSCODING, ERNAME, ERDESC, ERSTATUS, ERLABEL, ERCODE, ERPARCODE, ERCREATETIME, ERUSERID, ERUSERNAME, FINGERPRINT)
VALUES(0, '', '应急资源', '应急资源', '1', '', '000', '', '', '', '', '');


 --eventss数据
 INSERT INTO EVENTSS
(EVENTID, EVENTNAME, LABELS, EVENTDES, FINGERPRINT)
VALUES(2, '严重突发事件（Ⅱ级）', 1, '1.在业务服务时段内，部分分支机构和网点全部重要业务中断
2.在业务服务时段内，部分分支机构和网点部分重要业务中断
', NULL);
INSERT INTO EVENTSS
(EVENTID, EVENTNAME, LABELS, EVENTDES, FINGERPRINT)
VALUES(3, '灾难突发事件（Ⅰ级）', 2, '1.在业务服务时段内，全行范围内所有重要业务中断
2.在业务服务时段内，全行范围内部分重要业务中断
', NULL);
 INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(8, 3, '一个', '单家', '480分钟(含)以上', NULL);
INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(2, 2, '一个(含)以上', '多家', '120分钟(含)以上', NULL);
INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(4, 2, '一个(含)以上', '单家', '240分钟(含)以上', NULL);
INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(7, 3, '两个(含)以上', '单家', '240分钟(含)以上', NULL);
INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(3, 2, '两个(含)以上', '单家', '120分钟(含)以上', NULL);
INSERT INTO SCOPES
(SCOPEID, EVENTID, IMPSCOPE, IMPBUS, IMPTIME, FINGERPRINT)
VALUES(6, 3, '一个(含)以上', '多家', '240分钟(含)以上', NULL);



  --soc0117添加场景数据
INSERT INTO SOC0117
(EID, ENAME, ELABEL, EDESC, ESTATUS, ECATEGORY, EKEY1, EKEY2, EKEY3, ESYSCODING, EPARCODING, FINGERPRINT, EMODELTYPE)
VALUES('CM60000000', '场景', 'CJ', NULL, '1', '060', '0', NULL, NULL, '999060', '999', NULL, NULL);
INSERT INTO SOC0117
(EID, ENAME, ELABEL, EDESC, ESTATUS, ECATEGORY, EKEY1, EKEY2, EKEY3, ESYSCODING, EPARCODING, FINGERPRINT, EMODELTYPE)
VALUES('CM888001001', '预案', '080', '', '1', '080', NULL, NULL, NULL, '888001', '888', NULL, NULL);
--soc0119
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001006', 'CM60000000', '是否已演练', NULL, NULL, NULL, '1', 2, '001', '520', '2', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001004', 'CM60000000', '场景应急处置步骤', NULL, NULL, NULL, '1', 2, '001', NULL, '0', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001001', 'CM60000000', '场景名称', NULL, NULL, NULL, '1', 2, '001', NULL, '0', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001007', 'CM60000000', '定义场景流程ID', NULL, NULL, NULL, '1', 2, '001', NULL, '0', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001002', 'CM60000000', '场景描述', NULL, NULL, NULL, '1', 2, '001', NULL, '6', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001008', 'CM60000000', '场景类型', NULL, NULL, NULL, '1', 2, '001', NULL, '0', '999060', NULL, '0', NULL);
INSERT INTO SOC0109
(CID, EID, CNAME, CLABEL, CDESC, CUNIT, CSTATUS, CSEQ, CCATEGORY, COPTION, CATTACH, ESYSCODING, FINGERPRINT, CREQUIRED, CORDER)
VALUES('CI600000001003', 'CM60000000', '预计恢复时间', NULL, NULL, NULL, '1', 2, '001', NULL, '7', '999060', NULL, '0', NULL);
--增加应急制度资产
INSERT INTO SOC0117
(EID, ENAME, ELABEL, EDESC, ESTATUS, ECATEGORY, EKEY1, EKEY2, EKEY3, ESYSCODING, EPARCODING, FINGERPRINT, EMODELTYPE)
VALUES('CM1001002', '应急制度', NULL, '应急制度', '1', '013', NULL, NULL, NULL, '999013002', '999013', NULL, ' ');


INSERT INTO IG555
(JUMP, URL, DESCRIPTION, FINGERPRINT)
VALUES('97', 'IGDRM1901.do', NULL, NULL);

