--执行存储过程脚本 db2 -td@ -f ig333pro.sql 

connect to ig user db2inst1 using db2inst1
@
CREATE OR REPLACE PROCEDURE PRO_IG333 (V_PDID VARCHAR(64),V_PDID_NEW VARCHAR(64))
BEGIN
    INSERT INTO IG333
    (
	PSDID,
	PDID,
	PSDNAME,
	PSDDESC,
	PSDCODE,
	FINGERPRINT,
	PSDTYPE,
	PSDMODE,
	PSDFLAG,
	PSDASSIGN,
	PSDORG,
	PSDCONFIRM,
	ASSIGNPSDID,
	ASSIGNPBDID,
	ASSIGNFLAG,
	FORMGLOBALCONTROL,
	PARTICIPANTCHANGE,
	ASSIGNPAGETYPE,
	PPSDID,
	PSDXML,
	BRANCHCOND,
	JSFUNCTION,
    BYSEQUENCE
    )
    SELECT
	REPLACE(PSDID, V_PDID, V_PDID_NEW) AS PSDID_NEW,
	V_PDID_NEW AS PDID_NEW,
	PSDNAME,
	PSDDESC,
	PSDCODE,
    REPLACE(FINGERPRINT, V_PDID, V_PDID_NEW) AS FINGERPRINT,
	PSDTYPE,
	PSDMODE,
	PSDFLAG,
	PSDASSIGN,
	PSDORG,
	PSDCONFIRM,
	REPLACE(ASSIGNPSDID, V_PDID, V_PDID_NEW) AS ASSIGNPSDID,
	ASSIGNPBDID,
	ASSIGNFLAG,
	FORMGLOBALCONTROL,
	PARTICIPANTCHANGE,
	ASSIGNPAGETYPE,
	PPSDID,
	PSDXML,
	BRANCHCOND,
	JSFUNCTION,
    BYSEQUENCE
    FROM IG333
    WHERE PSDID LIKE V_PDID||'%'
    ORDER BY PSDID;
end
@
connect reset
@
