
/* Drop Tables */

DROP TABLE IF EXISTS SOC0501;
DROP TABLE IF EXISTS SOC0502;
DROP TABLE IF EXISTS IG.LOGINFO;




/* Create Tables */

CREATE TABLE SOC0501
(
	PID INTEGER NOT NULL,
	PWDTYPE VARCHAR(32),
	USERNAME VARCHAR(32),
	PWD VARCHAR(32),
	PWDDESCRIPTION VARCHAR(256),
	REGDATE CHAR(10),
	SERVERIP VARCHAR(32),
	PRIMARY KEY (PID)
) WITHOUT OIDS;


CREATE TABLE SOC0502
(
	RID INTEGER NOT NULL,
	PID INTEGER,
	RDESCRIPTION VARCHAR(32),
	RNAME VARCHAR(32),
	SERVERIP VARCHAR(32),
	OPERATIONINFO VARCHAR(512),
	REGDATE CHAR(10),
	PRIMARY KEY (RID)
) WITHOUT OIDS;


CREATE TABLE IG.LOGINFO
(
	LID INTEGER NOT NULL,
	LOGNAME VARCHAR(32),
	WARNTYPE VARCHAR(4),
	CITYPE VARCHAR(32),
	LOGSTATUS VARCHAR(32),
	LOGCONTENT VARCHAR(1024),
	LOGDATE CHAR(16),
	TOTALSIZE VARCHAR(32),
	USERSIZE VARCHAR(32),
	SURPLUSSIZE VARCHAR(32),
	USERRATIO VARCHAR(32),
	SERVERIP VARCHAR(32),
	PRIMARY KEY (LID)
) WITHOUT OIDS;



